// Original introductory summaries; no publication prose, image, logo or animation is imported.
export const majorOrganFunctionReferences = {
  digestive: 'https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works',
  gallbladder: 'https://www.cancer.gov/publications/dictionaries/cancer-terms/def/gallbladder',
  pancreas: 'https://training.seer.cancer.gov/anatomy/endocrine/glands/pancreas.html',
  kidney: 'https://www.niddk.nih.gov/health-information/kidney-disease/kidneys-how-they-work',
  urinary: 'https://www.niddk.nih.gov/health-information/urologic-diseases/urinary-tract-how-it-works',
  respiratory: 'https://www.nhlbi.nih.gov/health/lungs/respiratory-system',
  spleen: 'https://training.seer.cancer.gov/anatomy/lymphatic/components/spleen.html',
  adrenal: 'https://training.seer.cancer.gov/anatomy/endocrine/glands/adrenal.html',
  adrenalHormones: 'https://www.niddk.nih.gov/health-information/endocrine-diseases/adrenal-insufficiency-addisons-disease/definition-facts',
} as const;

const niddk='Source: National Institute of Diabetes and Digestive and Kidney Diseases; National Institutes of Health; U.S. Department of Health and Human Services.';
const nci='Source: National Cancer Institute, Surveillance, Epidemiology, and End Results Program.';

export const majorOrganFunctionTopics = {
  pancreas:{title:'Digestive & endocrine roles',body:'The pancreas has exocrine and endocrine roles. Digestive enzymes made by exocrine tissue travel through ducts to the small intestine, while endocrine islet cells release hormones into blood; insulin and glucagon are central regulators of blood glucose.',bullets:['Within pancreatic islets, beta cells release insulin and alpha cells release glucagon; these examples are not a complete account of islet cell types or hormones.','The displayed envelope and duct-source components do not establish duct-lumen continuity, microscopic acini or islet anatomy, and the omitted near-coincident parenchymal alternative remains archived.',`${niddk} Additional source: National Cancer Institute, Surveillance, Epidemiology, and End Results Program.`],references:['digestive','pancreas']},
  stomach:{title:'Storage, mixing & onward movement',body:'The stomach temporarily holds swallowed food and mixes it with gastric acid and digestive enzymes. This mixing and chemical digestion precede controlled onward delivery to the duodenum.',bullets:['Muscular mixing and emptying are dynamic processes coordinated with the rest of the digestive tract.','This root surface does not separate functional wall layers or animate mixing and emptying.',niddk],references:['digestive']},
  smallIntestine:{title:'Digestion & absorption',body:'The small intestine receives material from the stomach and is a principal site where digestion continues and nutrients are absorbed. Its contents are moved and mixed by coordinated muscular activity before remaining material reaches the large intestine.',bullets:['Digestive secretions from the pancreas, liver and small intestine contribute to breakdown of food.','This aggregate excludes the separately selectable ileocecal junction and does not represent mucosal microstructure, peristalsis or measured absorption.',niddk],references:['digestive']},
  largeIntestine:{title:'Water recovery & stool movement',body:'The large intestine absorbs water from remaining digestive contents and moves waste towards elimination. Bacterial activity and coordinated muscular movement also contribute to formation and passage of stool.',bullets:['Its role differs from the small intestine’s predominant digestion and nutrient-absorption work.','This aggregate excludes the separately selectable rectum and ileocecal junction and does not animate motility or establish transit, patency or continence.',niddk],references:['digestive']},
  gallbladder:{title:'Bile storage & release',body:'The gallbladder stores and concentrates bile between meals and releases it into the small intestine, where bile helps with fat digestion. Bile is produced by the liver, not by the gallbladder.',bullets:['Storage and release are coordinated with the biliary and digestive systems.','This abdominal organ is carried in a legacy pelvis-organ bundle; the surface does not establish duct patency, contraction or bile flow.','Sources: National Institute of Diabetes and Digestive and Kidney Diseases; National Cancer Institute Dictionary of Cancer Terms.'],references:['digestive','gallbladder']},
  kidney:{title:'Filtration, balance & endocrine roles',body:'Blood filtration begins in the kidney’s glomeruli; kidney tubules then return needed water and substances to blood and add other material to urine. Together these processes help regulate fluid, electrolytes and acid–base balance, with endocrine roles in blood-pressure regulation, red-cell production and bone health.',bullets:['A surface shape cannot establish filtration rate, equal function between sides or an individual’s renal physiology.','Separately bound renal vascular detail provides nested context. The independent HRA renal specimen includes selected cortical and collecting structures, with three defective source surfaces withheld, but it is not registered to this root kidney.',niddk],references:['kidney']},
  bladder:{title:'Urine storage & coordinated voiding',body:'The urinary bladder stores urine delivered by the ureters until coordinated voiding. Emptying involves bladder-wall contraction, outlet relaxation and neural control rather than the bladder surface acting alone.',bullets:['Storage and voiding are distinct phases of lower urinary-tract function.','This pelvic root surface is not an animated emptying or capacity model and does not establish patency, continence, pressure or quantitative capacity.',niddk],references:['urinary']},
  esophagus:{title:'Swallowed-material transport',body:'The esophagus conveys swallowed food and liquid from the throat towards the stomach. Coordinated muscular waves called peristalsis propel material along this route.',bullets:['Transport through the esophagus is one step in a longer digestive sequence.','Its thoracic navigation grouping does not mean the full esophageal course is exclusively thoracic; this surface does not animate swallowing, peristalsis or sphincter function.',niddk],references:['digestive']},
  trachea:{title:'Air conduction',body:'The trachea conducts air between the larynx and the main bronchi on the route to and from the lungs. It is part of the conducting airway; oxygen and carbon-dioxide exchange occurs farther downstream at alveolar surfaces.',bullets:['Air conduction is distinct from ventilation mechanics and alveolar gas exchange.','The existing airway and lung context is static and does not simulate ventilation, airflow, changes in airway calibre or gas transfer.','Source: National Heart, Lung, and Blood Institute; National Institutes of Health; U.S. Department of Health and Human Services.'],references:['respiratory']},
  spleen:{title:'Blood filtration & immune surveillance',body:'The spleen filters blood, helps remove old or damaged red blood cells and contributes to immune surveillance of blood-borne material. This differs from lymph nodes, which filter lymph.',bullets:['Its blood-filtering and immune roles depend on specialised internal tissue organisation.','This root surface does not separately segment red and white pulp or measure blood-cell removal, immune activity or reservoir behaviour.',nci],references:['spleen']},
  adrenal:{title:'Cortical & medullary hormones',body:'The adrenal cortex produces steroid hormones, including cortisol and aldosterone, while the adrenal medulla produces catecholamines. These signals contribute to metabolic and stress responses and to salt, water and blood-pressure regulation.',bullets:['Cortical steroid classes and medullary catecholamines arise from different regions of the gland; the named examples are not a complete hormone inventory.','This root surface does not independently separate cortical zones from medulla or establish hormone production, secretion or an individual’s endocrine function.','Sources: National Cancer Institute, Surveillance, Epidemiology, and End Results Program; National Institute of Diabetes and Digestive and Kidney Diseases.'],references:['adrenal','adrenalHormones']},
} as const;
