// Original short adaptations; no figures, clinical cases, scans or protocols.
export const portalHepaticClinicalReferences = [
  'https://doi.org/10.1007/s13244-015-0419-8',
  'https://doi.org/10.1007/s00423-026-04049-8',
  'https://doi.org/10.3390/diagnostics13132256',
  'https://creativecommons.org/licenses/by/4.0/',
] as const;

export const portalHepaticClinicalCredit = 'Original adapted teaching: Arora A et al., collateral pathways in portal hypertension (2015); Kotecha K et al., gastric venous congestion after pancreatic surgery (2026); Porrello G, Mamone G, Miraglia R, Budd-Chiari imaging review (2023). All three articles: CC BY 4.0. No endorsement implied; no publication media or patient cases included.';

export const portalHepaticClinicalTopics = {
  splenic: {
    clinical: {
      title: 'Splenic return & pancreatic neighbourhood',
      body: 'Follow splenic venous return behind the pancreas towards the portal confluence. Its relationship to the pancreas matters when reviewing regional disease or postoperative anatomy. Identify the splenic vein separately from the splenic artery and from the hepatic veins: these names describe different circulation pathways.',
      prompt: 'Study question: is this liver inflow or outflow? Splenic return contributes to portal inflow; selecting the surface does not demonstrate a patient confluence or a patent lumen.',
    },
    pathology: {
      title: 'Splenic outflow obstruction & regional hypertension',
      body: 'Impaired splenic venous drainage can produce sinistral, or left-sided, portal hypertension with gastric collateral enlargement. This regional mechanism is not interchangeable with diffuse portal hypertension from liver disease. The obstruction, collateral routes and their clinical significance must be established in the individual patient.',
      prompt: 'A missing model connection is not splenic vein thrombosis. No varices, pressure measurements or collateral flow are generated by selecting or exploding this source.',
    },
  },
  gastroLeft: {
    clinical: {
      title: 'Greater-curvature drainage towards the spleen',
      body: 'The left gastroepiploic, or gastro-omental, vein contributes gastric drainage towards the splenic vein. Compare it with the right gastroepiploic route towards superior mesenteric return. These routes explain why assessing the stomach requires more than identifying one named venous surface.',
      prompt: 'Distinguish this greater-curvature vessel from the left gastric vein near the lesser curvature. Their similar names do not make their drainage destinations or patient findings interchangeable.',
    },
    pathology: {
      title: 'Loss of splenic-side gastric drainage',
      body: 'Pancreatic or splenic-region surgery can disrupt the left gastroepiploic and associated gastric venous pathways. Reduced outflow may contribute to gastric congestion, depending on which alternative routes remain. This is a drainage-network problem, not a diagnosis made from the appearance of one atlas vein.',
      prompt: 'Do not equate hiding this vessel with an operation or predict congestion from that action. The model has no postoperative haemodynamics or validated compensatory channels.',
    },
  },
  gastroRight: {
    clinical: {
      title: 'Greater-curvature drainage towards the mesentery',
      body: 'The right gastroepiploic, or gastro-omental, vein contributes gastric return towards the superior mesenteric vein. Its collecting arrangement varies. Keep this venous route distinct from the accompanying arterial supply when orienting to pancreatic and gastric imaging.',
      prompt: 'Trace the named right-sided drainage direction, but do not bridge source gaps or treat this selection as a validated gastrocolic collecting trunk.',
    },
    pathology: {
      title: 'Mesenteric-side outflow & gastric congestion',
      body: 'Loss of gastric venous drainage during pancreatic surgery can cause congestion even when arterial supply is present. The right gastroepiploic route is one contributor to that outflow network. Whether other channels compensate is a patient-specific question, not a property of the reference mesh.',
      prompt: 'Why does an artery alone not prove adequate drainage? Inflow and venous outflow are separate questions; no surgical reconstruction or treatment recommendation is supplied here.',
    },
  },
  gastricLeft: {
    clinical: {
      title: 'Lesser-curvature route & variable termination',
      body: 'The left gastric vein is associated with the lesser curvature and upper stomach. Its termination can vary, including portal or splenic venous drainage. A named atlas source helps orientation, but patient imaging is needed to determine the actual route before assigning a linked finding.',
      prompt: 'Compare left gastric with left gastroepiploic, then identify the possible collecting pathways. A typical teaching route is not a guarantee of the same confluence in every patient.',
    },
    pathology: {
      title: 'Left gastric vein & gastro-oesophageal collaterals',
      body: 'In portal hypertension, the left gastric vein can supply gastro-oesophageal collateral pathways. Distinguish varices within the oesophageal wall from para-oesophageal collaterals outside it. The selected source does not contain those fine branches or establish a varix, active bleeding or bleeding risk.',
      prompt: 'Relate the named vein to the lower oesophageal region without inventing a vessel connection. A collateral pathway needs acquired imaging evidence, not merely nearby surfaces.',
    },
  },
  gastricRight: {
    clinical: {
      title: 'Right lesser-curvature drainage',
      body: 'The right gastric vein is a lesser-curvature gastric drainage route, separate from the greater-curvature right gastroepiploic vein. Compare both before linking a gastric or pancreatic-region finding. The word right in a vessel name does not require every point of its course to lie on the right of the midline.',
      prompt: 'Select the right gastroepiploic vein separately. Do not copy a finding or a presumed termination between these two similarly named structures.',
    },
    pathology: {
      title: 'Remaining drainage & venous congestion',
      body: 'Gastric congestion can follow disruption of several venous outflow routes. The right gastric vein is one pathway to consider when assessing what drainage remains; its presence alone does not prove that overall outflow is sufficient. No risk estimate can be derived from its displayed diameter.',
      prompt: 'Assess the network rather than counting visible veins. The reference model supplies no postoperative state, pressure, flow capacity or evidence that remaining channels compensate.',
    },
  },
  hepaticMiddle: {
    clinical: {
      title: 'Hepatic outflow versus portal inflow',
      body: 'The middle hepatic vein carries blood away from the liver towards the inferior vena cava. Portal venous inflow is a different pathway. This distinction helps avoid assigning an outflow finding to a portal branch when moving between anatomy and patient imaging.',
      prompt: 'Study question: which end of hepatic circulation is represented? This whole source-labelled surface is not a validated segmental drainage map or an operative boundary.',
    },
    pathology: {
      title: 'Budd-Chiari: identify the outflow problem',
      body: 'Budd-Chiari syndrome involves impaired hepatic venous outflow, excluding right-heart failure and constrictive pericarditis as the explanation. Thrombosis, invasion or external compression can obstruct outflow. This is distinct from portal vein thrombosis, although both may coexist.',
      prompt: 'A narrowed-looking model does not diagnose obstruction. The selected middle hepatic source supplies neither acquired luminal findings nor the cause or extent of a patient outflow lesion.',
    },
  },
  hepaticRight: {
    clinical: {
      title: 'Right tributary group is not seven named veins',
      body: 'This right hepatic tributary selection preserves four source files with seven disconnected components. They form one source-labelled group, not seven separately validated veins. Use it for orientation to right hepatic return, without assigning a drainage territory to each piece.',
      prompt: 'Compare the separate main hepatic-vein selections. Root and nested liver-branches sources retain different identities; a link must not silently substitute one representation for another.',
    },
    pathology: {
      title: 'Outflow obstruction & source gaps',
      body: 'Hepatic venous outflow obstruction can cause liver congestion. Its location and extent need clinical and imaging correlation. The seven disconnected components here are source geometry, not seven occlusions, collateral channels or regions of non-viable liver.',
      prompt: 'Do not interpret separation between pieces as thrombosis or add bridges to imply recanalisation. This group contains no validated lumen or patient enhancement information.',
    },
  },
  hepaticLeft: {
    clinical: {
      title: 'Left tributary group & representation limits',
      body: 'This left hepatic tributary group consists of five source files and five disconnected components. The left label identifies the source group; it does not certify a complete left-liver drainage tree or prove that each visible piece meets a main vein.',
      prompt: 'Count source components only as geometry evidence. Do not rename them as segmental veins or infer that a selected liver segment has been fully represented.',
    },
    pathology: {
      title: 'Chronic outflow disease & remodelling',
      body: 'Chronic hepatic outflow obstruction can be accompanied by fibrosis, altered liver form and collateral development. These are findings to evaluate in acquired studies, not changes simulated by this left tributary group. Its component count cannot establish disease chronicity or severity.',
      prompt: 'Moving the group leaves its original internal spacing intact. Explode mode is an inspection aid, not progression of fibrosis, collateral formation or a test of hepatic reserve.',
    },
  },
} as const;
