import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {atlasModules} from '../lib/catalog.ts';
const runtime=new URL('../public/atlas-runtime/head-neck/',import.meta.url);
const sha=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
test('head and neck delivery preserves the complete audited regional and nested scope',async()=>{
  const manifest=JSON.parse(await readFile(new URL('manifest.json',runtime),'utf8'));
  assert.match(manifest.sourceCommit,/^[a-f0-9]{40}$/);
  assert.equal(manifest.sourceCommit,'adad1abe1ad6fdb3c942d1d8b6a98393591bec80');
  const inputs=JSON.parse(await readFile(new URL('source-inputs.json',runtime),'utf8')) as {path:string;sha256:string}[];
  assert.equal(inputs.find(input=>input.path==='lib/regional-framing.ts')?.sha256,'96c4e2c9690fdc93b3caadea4a36bad91a038e95ec7da08a362aadf142d8b575','export includes the foot framing fallback source');
  assert.equal(manifest.region,'head-neck');assert.equal(manifest.structures,291);assert.equal(manifest.nestedSelections,77);
  assert.equal(new Set(manifest.regionalIds).size,291);
  assert.equal(new Set(manifest.nestedTargets.map((t:{structureId:string})=>t.structureId)).size,77);
  for(const key of ['clinicalApproved','patientDataIncluded','standaloneReviewConnection','imagingConnection'])assert.equal(manifest[key],false);
  const found:string[]=[];
  async function walk(base:URL,prefix=''){
    for(const item of await readdir(base,{withFileTypes:true})){
      assert(!item.isSymbolicLink());
      if(item.isDirectory())await walk(new URL(item.name+'/',base),prefix+item.name+'/');else found.push(prefix+item.name);
    }
  }
  await walk(runtime);
  assert.deepEqual(found.sort(),['manifest.json',...manifest.files.map((f:{path:string})=>f.path)].sort());
  for(const file of manifest.files){
    assert(!file.path.includes('..')&&!file.path.startsWith('/'));
    assert(!/\.(dcm|nii|nrrd|stl|vmatlas|vmmr|vmcompare|map)(\.|$)/i.test(file.path));
    const bytes=await readFile(new URL(file.path,runtime));assert.equal(bytes.length,file.bytes);assert.equal(sha(bytes),file.sha256);
  }
  assert.equal(manifest.schemaVersion,2);
  assert.deepEqual(manifest.regionalScopes.map((s:{region:string;regionalIds:string[];nestedTargets:unknown[]})=>[s.region,s.regionalIds.length,s.nestedTargets.length]),[['head-neck',291,77],['thorax',158,11],['abdomen',106,16],['pelvis',82,4],['spine',115,0],['shoulder-arm',115,0],['forearm',86,0],['hand',124,0],['thigh',95,4],['leg',76,4],['foot',122,0],['whole-body',1104,108]]);
  assert.equal(found.filter(p=>p.endsWith('.glb')).length,136);
  for(const bundle of manifest.modelBundles){
    const bytes=await readFile(new URL(bundle.url.split('?')[0].slice(1),runtime));
    assert.equal(sha(bytes),bundle.sha256);assert.equal(bytes.length,bundle.bytes);
  }
});
test('head and neck keeps exact generated bytes and compatible full notices',async()=>{
  assert((await readFile(new URL('../.gitattributes',import.meta.url),'utf8')).includes('public/atlas-runtime/head-neck/** -text'));
  const html=await readFile(new URL('index.html',runtime),'utf8');
  for(const match of html.matchAll(/(?:src|href)="([^"]+)"/g)){
    assert(match[1].startsWith('/atlas-runtime/head-neck/'));await readFile(new URL(match[1].slice('/atlas-runtime/head-neck/'.length),runtime));
  }
  const deps=JSON.parse(await readFile(new URL('bundled-dependencies.json',runtime),'utf8'));
  const notices=await readFile(new URL('BUNDLED_NOTICES.txt',runtime),'utf8');
  assert(deps.length>10);
  for(const d of deps){assert(['MIT','ISC','Apache-2.0','BSD-2-Clause','BSD-3-Clause','CC0-1.0','0BSD'].includes(d.license));assert(notices.includes(d.name+'@'+d.version));}
  const credits=await readFile(new URL('models/bodyparts3d/credits.html',runtime),'utf8');
  assert(credits.includes('The Database Center for Life Science')&&credits.includes('CC Attribution 4.0'));
  for(const match of credits.matchAll(/href="([^"]+)"/g)){
    if(match[1].startsWith('https:'))continue;
    if(match[1].startsWith('/')){
      assert.equal(match[1],'/atlas');
      await readFile(new URL('../app/atlas/page.tsx',import.meta.url));
    }else await readFile(new URL(match[1],new URL('models/bodyparts3d/',runtime)));
  }
});
test('head and neck uses the compact host layout and does not claim imaging access',async()=>{
  const entries=atlasModules.filter(m=>m.slug==='head-neck-3d');assert.equal(entries.length,1);assert.equal(entries[0].images,0);assert.equal(entries[0].structures,291);
  const page=await readFile(new URL('../app/atlas/head-neck-3d/page.tsx',import.meta.url),'utf8');
  assert.equal((page.match(/<iframe\b/g)||[]).length,1);assert(page.includes('src="/atlas-runtime/head-neck/index.html"'));
  assert(page.includes('No scan or spatial registration is connected'));assert(page.includes('lecture access remains separate'));
  const frame=await readFile(new URL('../components/SiteFrame.tsx',import.meta.url),'utf8');assert(frame.includes("pathname === '/atlas/head-neck-3d'"));
});
