// Original concise adaptations; no figures, scans, case details or procedures.
export const genicularClinicalReferences = [
  'https://doi.org/10.3390/jcm14062106',
  'https://doi.org/10.1007/s00270-023-03411-3',
  'https://doi.org/10.1016/j.ijscr.2020.02.050',
  'https://creativecommons.org/licenses/by/4.0/',
] as const;
export const genicularClinicalCredit = 'Original abbreviated adaptations: Brown JM et al. (2025), genicular arterial anatomy review; Callese TE et al. (2023), genicular branching variants; Glanz L (2020), superolateral genicular pseudoaneurysm case report. Articles: CC BY 4.0. No endorsement, publication figures, patient cases or treatment protocols included.';

export const genicularClinicalTopics = {
  middle: {
    clinical: {
      title: 'Deep intra-articular route',
      body: 'The middle genicular artery passes through the posterior capsule towards the intercondylar region and contributes to cruciate and synovial vascular supply. Distinguish this deep route from the peripheral genicular network. Each displayed middle-genicular source retains two disconnected components under one original label.',
      prompt: 'Two components do not mean two named arteries. Do not bridge them or infer a continuous course through the capsule from their source label alone.',
    },
    pathology: {
      title: 'Vascular supply is not ligament integrity',
      body: 'A vessel associated with cruciate supply does not establish whether a ligament is torn, viable or healing. Keep the vascular reference separate from structural assessment of the cruciates and from evidence of synovial disease in an individual knee.',
      prompt: 'A source gap is not arterial occlusion. No MRI ligament appearance, microvascular perfusion or postoperative graft viability is generated by selecting this artery.',
    },
  },
  medialSuperior: {
    clinical: {
      title: 'Superior medial condylar neighbourhood',
      body: 'Orient this vessel to the medial femoral epicondylar region, rather than the inferior medial tibial route. It belongs to the peripheral knee network. The superior and middle genicular branches may share an origin; separately named structures do not guarantee independent popliteal ostia.',
      prompt: 'Compare the same-side popliteal parent and middle branch using Arterial connections. A conceptual parent line is not confirmation of the branching variant in this specimen or patient.',
    },
    pathology: {
      title: 'Synovial vascularity needs acquired evidence',
      body: 'Knee osteoarthritis can include synovial inflammation and abnormal vascular proliferation. The presence of a normal named genicular artery is not evidence of that process, and the side of pain alone cannot identify a responsible branch.',
      prompt: 'The reference model has no synovial enhancement, Doppler activity or angiographic blush. Selecting the medial superior branch does not diagnose synovitis or identify a treatment target.',
    },
  },
  lateralSuperior: {
    clinical: {
      title: 'Lateral superior branch identification',
      body: 'Locate the superior lateral selection separately from the inferior lateral route. A shared origin with the middle genicular artery is a described branching pattern, not a diagnosis or a junction that this mesh collection proves.',
      prompt: 'Use anatomical names and source positions together. Rotating or separating the models does not reveal a previously unmeasured common trunk.',
    },
    pathology: {
      title: 'Postoperative pseudoaneurysm context',
      body: 'Superior lateral genicular pseudoaneurysm has been reported after knee ligament reconstruction. A postoperative pulsatile swelling can represent vascular injury even without marked pain. Clinical assessment and acquired vascular imaging establish the lesion and its feeding vessel; the reference artery alone cannot do so.',
      prompt: 'The cited report is an example, not a frequency estimate or universal diagnostic pathway. No patient image, pseudoaneurysm sac or treatment technique is reproduced here.',
    },
  },
  medialInferior: {
    clinical: {
      title: 'Medial tibial and collateral-ligament relationship',
      body: 'The inferior medial route turns around the medial tibial condyle and passes deep to the medial collateral ligament. Compare this tibial-level neighbourhood with the superior medial femoral route. These are anatomical landmarks, not measured safe distances or procedural corridors.',
      prompt: 'Find the source on the same side in either the thigh or lower-leg workspace. Changing region does not change its arterial identity or validate its small branches.',
    },
    pathology: {
      title: 'Adjacent ligament injury is a separate finding',
      body: 'A medial collateral ligament abnormality and an arterial abnormality are different observations. A shared anatomical neighbourhood does not prove that both are injured, and a visible reference vessel does not exclude a vascular complication in a symptomatic knee.',
      prompt: 'Keep the questions separate: which tissue is abnormal, what demonstrates vascular involvement, and which vessel is actually involved? No scan or patient finding is supplied by this surface.',
    },
  },
  lateralInferior: {
    clinical: {
      title: 'Lateral tibial plateau and fibular-head context',
      body: 'The inferior lateral genicular route courses near the lateral tibial plateau and posterolateral structures, contributing around the fibular head before travelling anteriorly. Distinguish it from the superior lateral vessel and from nearby non-arterial structures.',
      prompt: 'Use the tibial-level landmarks for orientation, not the artificial distance between exploded parts. Return separation to zero before comparing source relationships.',
    },
    pathology: {
      title: 'Localisation is not a branch-specific diagnosis',
      body: 'Lateral knee symptoms or postoperative swelling cannot be assigned to this branch from location alone. The clinical task is to establish whether a vascular lesion is present and then localise its origin, rather than infer a lesion from the atlas label.',
      prompt: 'No Doppler signal, contrast filling or validated supply territory is encoded in this mesh. An absent display connection is not a thrombosed branch, and a touching surface is not proof of patency.',
    },
  },
} as const;
