// The human summary and JSON inventory are generated and freshness-checked together.
export function renderRequirementSummary(report) {
  const {
    anatomy,
    study,
    teaching,
    practice,
    assetsAndRights,
    learningIntegration,
  } = report;
  const names = {
    anatomy: 'Anatomy',
    function: 'Function',
    ct: 'CT',
    mri: 'MRI',
    xray: 'X-ray',
    ultrasound: 'Ultrasound',
    pathology: 'Pathology',
    clinical: 'Clinical',
    quiz: 'Quiz notes',
  };
  const rows = Object.entries(names)
    .map(([tab, title]) => {
      const counts = teaching.body[tab];
      return `| ${title} | ${counts.specificDraft} | ${counts.identityOnly} | ${counts.pending} | ${counts.generatedIdentification} |`;
    })
    .join('\n');
  return `# Current atlas status

[Independent specimen reviews](SPECIMEN_REVIEWS.md) now cover 82 HRA kidney and 41 female-pelvis selections in a separate append-only private store. Exact specimen, source frame, geometry, teaching and checklist revisions are bound to each record; no shoulder/body approval transfers. Anatomy and teaching are reviewed separately, acquired-imaging approval remains unavailable, and other specimen adapters are still pending. This inventory reads no personal review records and asserts no clinical sign-off or hosted rollout.

[Lower-limb arterial imaging](LOWER_ARTERIAL_IMAGING.md) supplies ${anatomy.lowerArterialImaging.selections} existing artery selections with CT/MRI/US drafts (${Object.values(anatomy.lowerArterialImaging.modalities).reduce((a,b)=>a+b,0)} placements / ${anatomy.lowerArterialImaging.distinctTopicTexts} regional-modality texts). Six concept-specific cautions and the existing inspector keep navigation compact. Missing fibular/trunk selections, complete runoff, scans, registration and radiologist/device approval remain outstanding.

[Deep-brain septal landmarks](LIMBIC_LANDMARKS.md) adds ${anatomy.limbicLandmarks.sourceSelections} complete source selections / ${anatomy.limbicLandmarks.originalTriangles} retained triangles and one compact study with ${anatomy.limbicLandmarks.contextSelections} context records. Lamina point-contact, septal compound and stria laterality limits are explicit; the defective stria-terminalis source remains offline. Eleven introductory draft placements do not constitute comprehensive teaching, complete circuits, clinical/device acceptance or patient registration.

[Separate back layers](BACK_LAYERS_SPECIMEN.md) adds ${anatomy.backLayersSpecimen.muscleSurfaces} source muscle surfaces with ${anatomy.backLayersSpecimen.skeletalContext} same-source bones and ${anatomy.backLayersSpecimen.studies} reversible studies. All ${anatomy.backLayersSpecimen.triangles} original triangles remain in a separate version-3 frame; source fragments are disclosed. [Detailed teaching](BACK_LAYERS_TEACHING.md) supplies attachments/motor notes for ${anatomy.backLayersSpecimen.attachmentMotorDrafts} selections and ${Object.values(anatomy.backLayersSpecimen.extendedTopicDrafts).reduce((a,b)=>a+b,0)} extended draft placements using ${anatomy.backLayersSpecimen.distinctExtendedTopicTexts} topic texts and ${anatomy.backLayersSpecimen.distinctClinicalSelfChecks} clinical self-checks. Existing collapsed controls are reused; unsupported topics remain pending. No complete back stack, fascia, discs, nerve path, scan registration or clinical approval is supplied. Separate CC BY-SA 2.1 Japan asset terms remain; main-body counts are unchanged.

[Pelvic venous tributaries](PELVIC_VEINS.md) adds ${anatomy.pelvicVeins.sourceSelections} original vein selections and ${anatomy.pelvicVeins.originalTriangles} retained triangles, with ${anatomy.pelvicVeins.contextSelections} existing context selections in one compact Study. Two left-labelled definitions remain offline for coordinate/laterality adjudication. Introductory orientation/self-check notes and three drainage notes are drafts; other functional, clinical and imaging topics remain pending. No complete network, joined lumen or clinical/device acceptance is claimed.

[Inferior epigastric vessels](INFERIOR_EPIGASTRIC_VESSELS.md) adds ${anatomy.inferiorEpigastricVessels.sourceSelections} original arterial/venous selections and ${anatomy.inferiorEpigastricVessels.originalTriangles} retained triangles. One focused abdominal-wall Study pairs them with ${anatomy.inferiorEpigastricVessels.contextSelections} existing vascular references, without adding a permanent toolbar. Anatomy, Function, inguinal-orientation and self-check are drafts. Fascia, rings, complete perforators, joined lumens, acquired scans and clinical/device acceptance remain absent or pending.

[Male pelvis: deferent ducts](DEFERENT_DUCTS.md) adds ${anatomy.deferentDucts.sourceSelections} original selections and ${anatomy.deferentDucts.originalTriangles} retained source triangles. The existing Study menu combines them with ${anatomy.deferentDucts.contextSelections} nearby organ selections, side filtering and reversible removal. Search accepts vas/ductus deferens. Anatomy, Function and self-check are drafts; clinical/imaging teaching and device acceptance remain pending. No generated junction, continuous lumen or patient correspondence is claimed.

[Original-resolution batching](BODY_BATCHING.md) groups ${report.rendering.bodyBatching.batchedSurfaces} compatible opaque surfaces into ${report.rendering.bodyBatching.batches} batches in the all-visible whole-body CPU model. Original geometry, anatomical identities and existing controls are retained; selected/transparent/cut/muscle surfaces and small views keep individual rendering. Unsupported devices fall back. This is not measured GPU performance, browser visual acceptance or clinical sign-off.

[Inferior thyroid arteries](INFERIOR_THYROID_ARTERIES.md) add ${anatomy.inferiorThyroidArteries.sourceSelections} original neck selections (${anatomy.inferiorThyroidArteries.originalTriangles} retained triangles), same-side thyrocervical navigation and ${anatomy.inferiorThyroidArteries.neckContextBones} existing context bones. Four muscle-part candidates remain offline source-condition evidence, not admitted geometry. No complete gland/nerve anatomy, joined lumen, clinical approval or patient registration is claimed.

[Genicular knee study](GENICULAR_ARTERIES.md#focused-knee-study) groups ${anatomy.genicularArteries.focusSourceSelections} original selections into one compact posterior view in Knee & leg and Whole body. Source-bound transitions, stable close-up framing and reversible removal reuse existing controls. Ten genicular source groups retain all ${anatomy.genicularArteries.originalTriangles} original triangles; disconnected middle-genicular pieces are not bridged. Clinical/device review and imaging registration remain outstanding.

[Inferior collicular brachia](COLLICULAR_BRACHIA.md) adds ${anatomy.nestedDissections.collicularBrachiaSelections} original neural surfaces (${anatomy.nestedDissections.collicularBrachiaOriginalTriangles} retained triangles) within brainstem dissection, with pair/midbrain views and source-bound auditory teaching. The ${anatomy.nestedDissections.collicularBrachiaLateralityHolds} superior candidates remain withheld for contradictory source laterality. Existing brainstem meshes are unchanged; no complete auditory pathway, fibre reconstruction, clinical approval or patient scan is supplied.

[Longus colli](LONGUS_COLLI.md) adds ${anatomy.longusColli.sourceSelections} source-preserving left muscle parts (${anatomy.longusColli.originalTriangles} triangles) and a focused study in Head & neck, Spine and Whole body. Use Both or Left; the right side is unavailable. Select parts, remove covering context and Undo without adding a permanent toolbar. Attachment geometry, fascial planes, clinical accuracy and imaging registration remain unvalidated.

[Hepatic veins](HEPATIC_VEINS.md) add ${anatomy.hepaticVeins.sourceSelections} genuine source groups with ${anatomy.hepaticVeins.originalTriangles} retained triangles from ${anatomy.hepaticVeins.sourceFiles} files. The middle hepatic vein and right/left tributary groups reuse selection, labels, dissection and the compact venous panel. All ${anatomy.hepaticVeins.sourceComponents} disconnected components remain in their original positions; no bridging, complete tree, Couinaud territory, flow or patient registration is claimed.

[Portal tributaries](PORTAL_VEINS.md) add ${anatomy.portalVeins.sourceSelections} genuine source meshes (${anatomy.portalVeins.originalTriangles} retained triangles): splenic and paired gastric/gastroepiploic veins. The existing selected-vein panel now connects ${anatomy.portalVeins.mappedSelections} portal selections through ${anatomy.portalVeins.mappedRelationships} typical relationships, with reversible isolation and no new toolbar. Variable mesenteric outlets and missing sinusoidal/collateral networks remain explicit. No flow, scan registration or clinical approval is supplied.

[Limb vascular dissection](LIMB_VASCULAR_STUDIES.md) adds ${anatomy.limbVascularStudies.studies} focused Study choices using ${anatomy.limbVascularStudies.sourceSelections} existing vessel, muscle and bone selections. Compare anterior/posterior calf and deep femoral relationships; hide a context muscle, extract a selected vessel and Undo. No permanent controls, new geometry, complete neurovascular bundle, surgical approach or imaging registration are supplied.

[Arm vascular dissection](ARM_VASCULAR_STUDIES.md) adds ${anatomy.armVascularStudies.studies} compact Study choices across Shoulder & arm and Whole body, using ${anatomy.armVascularStudies.sourceSelections} existing source selections. Compare brachial vessels with anterior flexors, or the deep brachial artery with triceps. Side filtering, muscle removal, extraction and Undo reuse existing controls. No new mesh, nerve path, fascial plane, complete paired veins, patient registration or clinical approval is supplied.

[Upper-limb vessel imaging](UPPER_VESSEL_IMAGING.md) adds source-bound introductory drafts for ${anatomy.upperVesselImaging.selections} existing selections: CT ${anatomy.upperVesselImaging.modalities.ct}, MRI ${anatomy.upperVesselImaging.modalities.mri}, US ${anatomy.upperVesselImaging.modalities.ultrasound}. These reuse ${anatomy.upperVesselImaging.distinctTopicTexts} topic texts across ${anatomy.upperVesselImaging.groups} groups with seven selection-specific cautions. Existing Imaging tabs are reused; superficial-vein CT/MRI and X-ray remain pending. No scan, flow, procedural clearance or clinical approval is supplied.

[Systemic venous drainage](SYSTEMIC_VENOUS_DRAINAGE.md) connects ${anatomy.venousDrainage.selections} existing source selections through ${anatomy.venousDrainage.relationships} typical relationships (${anatomy.venousDrainage.groups} groups). One collapsed selected-vein panel offers tributary/outlet navigation, cross-region links and reversible isolation with bones. Missing routes, variable small-saphenous outlets and unsegmented common-femoral regions remain explicit. Intracranial sinuses, portal/pulmonary/cardiac drainage and measured flow are not provided by this map.

[Focused elbow dissection](ELBOW_STUDIES.md) adds five Forearm studies using eight existing bone/muscle selections. Stable source-derived close-ups, real-surface labels and reversible windows reuse the existing Study controls. Whole structures remain intact; no new nerve, ligament, cartilage, simulated motion or scan correspondence is supplied.

[Wrist-bone imaging orientation](WRIST_IMAGING_TEACHING.md) adds 48 X-ray/CT/MRI drafts across sixteen existing carpal selections: five groups / fifteen distinct modality topics, with eight bone-specific cautions. The existing Imaging tabs are reused. No new surface, radiograph, CT voxel, MR signal, patient registration or clinical approval is supplied; ultrasound remains unchanged.

[Arterial connections](ARTERIAL_CONNECTIONS.md) offers upstream/downstream and communicating-neighbour exploration for ${anatomy.arterialConnections.selections} existing source selections through ${anatomy.arterialConnections.relationships} mapped relationships (${anatomy.arterialConnections.concepts} concepts; ${anatomy.arterialConnections.alternativeRelationships} alternative routes, not simultaneous donor connections). A selected-artery panel stays collapsed; regional isolation is reversible and outside neighbours use source-bound whole-body links. Missing segments remain explicit; no vessel lumen, flow or patient registration is invented.

[Lower-limb muscles by nerve](LOWER_LIMB_MOTOR.md) links ${anatomy.lowerLimbMotor.muscleSelections} existing root-body selections through ${anatomy.lowerLimbMotor.relationships} typical relationships in ${anatomy.lowerLimbMotor.groups} groups. Pelvis/hip, thigh, leg and foot reuse the same collapsed control as the upper limb. Source/frame checks and dissection history are retained; no nerve path or patient correspondence is invented. The independent lower-limb specimen remains separate.

[Private body reviews](BODY_REVIEW_DECISIONS.md) now record scoped decisions for root-body selections in a separate append-only store from the shoulder pilot. These records are not inspected by this inventory or propagated as clinical approval. Imaging approval remains unavailable without validated acquired resources.

[Upper-limb muscles by nerve](UPPER_LIMB_MOTOR.md) links ${anatomy.upperLimbMotor.muscleSelections} exact existing muscle selections through ${anatomy.upperLimbMotor.relationships} typical relationships across ${anatomy.upperLimbMotor.groups} nerve/branch groups. In Shoulder & arm, Forearm or Hand, choose Dissect → Muscles by nerve to show the group's available muscles with bone context. The control stays collapsed; left/right filters, selection and existing dissection history remain usable. Mixed supply and grouped surfaces are qualified. No nerve route, sensory field, lesion simulation, scan registration or clinical approval is added.

[Spinal imaging orientation](SPINE_IMAGING_TEACHING.md) adds 141 CT/MRI/X-ray topic drafts across 47 exact existing bone/disc source records: nine concept groups and 27 distinct modality topics, not 141 unique concepts. The existing compact Imaging panel and six focused level studies are retained. Other body teaching and geometry are unchanged; whole discs, unresolved T12–L1 geometry and absent neural tissues remain explicit. No patient scans, registration, paid-resource access or clinical approval are supplied.

[Separate kidneys](HRA_KIDNEY_SPECIMEN.md): ${anatomy.renalSpecimen.representations} original HRA surfaces / ${anatomy.renalSpecimen.triangles} retained triangles and ${anatomy.renalSpecimen.studies} guided studies. ${anatomy.renalSpecimen.anatomyFunctionDrafts} draft Anatomy/Function selections share ${anatomy.renalSpecimen.distinctAnatomyConcepts} concepts; ${anatomy.renalSpecimen.practiceTargets} non-lettered selections are eligible for identification. [Renal clinical/imaging detail](HRA_RENAL_TEACHING.md) adds ${anatomy.renalSpecimen.uniqueClinicalImagingTexts} topic texts across ${anatomy.renalSpecimen.clinicalImagingDrafts} placements, with ${anatomy.renalSpecimen.distinctClinicalSelfChecks} self-checks across ${anatomy.renalSpecimen.clinicalSelfChecks} selections. Unsupported topics remain pending. Three defective surfaces remain held; drainage correspondence, patient registration and clinical/device sign-off are not supplied. Main-body counts are unchanged.

[Separate female pelvis](HRA_FEMALE_PELVIS.md): ${anatomy.femalePelvicSpecimen.representations} original HRA surfaces, ${anatomy.femalePelvicSpecimen.studies} dissection studies and ${anatomy.femalePelvicSpecimen.anatomyFunctionDrafts} draft Anatomy/Function selections. The other ${anatomy.femalePelvicSpecimen.pendingTeaching} selections remain unavailable for teaching; six disputed/overlapping source groups are withheld. This independent CC BY 4.0 reference is not a complete female body or patient registration. Clinical/device sign-off is pending; main-body counts are unchanged.

[Pelvic teaching detail](HRA_FEMALE_PELVIS.md#structure-specific-teaching) now distinguishes ${anatomy.femalePelvicSpecimen.distinctAnatomyConcepts} anatomical concepts and adds ${anatomy.femalePelvicSpecimen.extendedTopicDrafts} extended draft placements / ${anatomy.femalePelvicSpecimen.clinicalSelfChecks} source-bound self-check placements. Clinical ${anatomy.femalePelvicSpecimen.extendedByTopic.clinical}, Pathology ${anatomy.femalePelvicSpecimen.extendedByTopic.pathology}, MRI ${anatomy.femalePelvicSpecimen.extendedByTopic.mri}, US ${anatomy.femalePelvicSpecimen.extendedByTopic.ultrasound} and CT ${anatomy.femalePelvicSpecimen.extendedByTopic.ct} remain introductory drafts, not unique lessons per placement, acquired imaging or approval. Existing compact tabs are reused; other topics explicitly remain pending.

[Abdominal-wall teaching](ABDOMINAL_WALL_SPECIMEN.md#detailed-teaching) supplies ${anatomy.abdominalWallSpecimen.detailedTeaching.anatomyFunctionDrafts} exact-source Anatomy/Function lessons, ${anatomy.abdominalWallSpecimen.detailedTeaching.attachmentDrafts} attachment/motor records, ${anatomy.abdominalWallSpecimen.detailedTeaching.extendedTopicDrafts} introductory clinical/pathology/imaging topics and ${anatomy.abdominalWallSpecimen.detailedTeaching.clinicalSelfChecks} self-checks. Three groups in the existing collapsed Learn panel keep the model prominent. Imaging notes explain recognition and limitations, not real scans or registration; source changes fail closed. Specialist validation remains pending.

[Abdominal identification practice](ABDOMINAL_WALL_SPECIMEN.md#identification-practice) covers ${anatomy.abdominalWallSpecimen.identificationPractice.muscleTargets} source muscles across ${anatomy.abdominalWallSpecimen.identificationPractice.studies.length} studies. Visible muscles alone enter rounds; bones stay contextual, labels/guides are hidden, and first-try/reveal/retry-missed scoring preserves the dissection history. Exact source/frame checks reject mismatches. This is source-label practice, not a clinical examination or approval.

[Separate abdominal-wall specimen](ABDOMINAL_WALL_SPECIMEN.md): ${anatomy.abdominalWallSpecimen.muscleSurfaces} version-3 muscle surfaces and ${anatomy.abdominalWallSpecimen.skeletalContext} partial skeletal context selections. Seven reversible studies expose the internal obliques, transversus and rectus pairs missing from the current body geometry. This is a separate source frame under ${anatomy.abdominalWallSpecimen.license}, with downloadable assets and reuse notices; not a registration into version 4 or a complete surgical wall. No source face is removed. Clinical, device and source-interface review remain pending.

[Lossless production model delivery](MODEL_DELIVERY.md) retains canonical source hashes and anatomical detail while reducing transport file size. Each production build checks decoded buffers and installed-loader scene equality for every model. Catalogue hashes/byte counts remain canonical, with separate transport hashes in the generated delivery manifest. This is not new anatomy, browser-performance or clinical certification.

[Muscles by nerve](UM_LIMB_MOTOR.md) links ${anatomy.independentSpecimens[0].detailedTeaching.motorExplorer.muscleSelections} source muscle selections through ${anatomy.independentSpecimens[0].detailedTeaching.motorExplorer.relationships} typical motor relationships across ${anatomy.independentSpecimens[0].detailedTeaching.motorExplorer.groups} nerve/branch groups. One collapsed control shows available targets with bone context and reversible visibility. Dual/variable supply is qualified; no nerve geometry or donor-specific innervation is supplied. [Peripheral-source candidates](PERIPHERAL_NERVE_CANDIDATES.md) remain unimported pending actual files, rights and spatial review.

[Independent lower-limb specimen](UM_LIMB_DISSECTION.md): ${anatomy.independentSpecimens[0].representations} unique selectable CC0 source surfaces across ${anatomy.independentSpecimens[0].regionalStudies.reduce((n, s) => n + s.studies, 0)} studies. Hip/thigh, calf, ankle/foot and an optional whole-limb view extend the unchanged 15-part knee study. Open from Pelvis & hip, Hip & thigh, Knee & leg or Ankle & foot. [Learning](UM_LIMB_LEARNING.md) includes ${anatomy.independentSpecimens[0].detailedTeaching.anatomyFunctionDrafts} source-bound anatomy/function drafts, ${anatomy.independentSpecimens[0].detailedTeaching.muscleAttachmentDrafts} muscle attachment/motor-supply records and visible-pool identification practice. Regional scopes overlap within one source subject; they are not added to the body below. Registration, clinical approval and further clinical/pathology/imaging teaching remain pending.

[Knee dissection studies](KNEE_STUDIES.md) add three compact views with automatic joint close-ups: bony relationships, patella set aside and posterior popliteus. Ten existing source representations remain whole; cartilage, ligaments and menisci are not added.

[Direct specimen links](UM_LIMB_NAVIGATION.md) open exact selections and studies across ${anatomy.independentSpecimens[0].navigation.scopes.length} scopes at available teaching topics. The dedicated page skips the other body model; mismatched sources/recipes and pending topics stop with a warning. Links grant neither separately paid-resource access nor scan registration.

[Independent clinical/imaging teaching](UM_LIMB_CLINICAL.md) adds ${Object.values(anatomy.independentSpecimens[0].detailedTeaching.extendedTopics).reduce((n, t) => n + t.draft, 0)} introductory topic drafts and ${anatomy.independentSpecimens[0].detailedTeaching.clinicalSelfChecks} clinical self-checks across hip/thigh, knee, calf and foot selections. Three compact groups reuse the Learn panel; pending topics remain explicit. These are source-bound educational drafts, not pathological meshes, patient images or clinical approval. The root-body counts below do not include them.

[Development priority](DEVELOPMENT_PRIORITIES.md) is the wider atlas and body regions; detailed oral work is deferred. Six [spinal-level studies](SPINAL_LEVEL_STUDIES.md) expose existing bone/disc groups with compact controls. T12–L1 is explicitly bones-only because its source disc is unresolved.

[Live camera direction](LIVE_CAMERA_ORIENTATION.md) now follows actual rotation in regional, whole-body and nested viewers. A reserved read-only line distinguishes model-left/right from screen position, without covering labels or expanding the page. It hides in exam/recovery states and does not imply patient-scan orientation. Anatomy counts and the dedicated shoulder renderer are unchanged.

[Wrist and foot bone exposure studies](ACRAL_BONE_STUDIES.md) add four compact Study choices using 30 existing bone representations, with no new geometry. Side filters, selection/removal and Undo/Redo reuse the established dissection controls. These are unvalidated source-bone arrangements, not cartilage, ligament or radiographic joint models.

Generated from the actual catalogue, teaching resolver, dissection profiles and question definitions. Run \`npm run requirements:audit\`; \`npm run requirements:audit -- --check\` checks this page and [the JSON inventory](requirement-audit.json) together. Historical milestone totals elsewhere are not current coverage.

## Delivered source scope

[X-ray orientation](XRAY_TEACHING.md) is available in the existing Imaging group: ${teaching.body.xray.specificDraft} source-pinned body drafts now include six shoulder-bone sources plus 47 spinal sources. The ${teaching.shoulder.xray.specificDraft} overlapping dedicated-shoulder drafts cover three shoulder-bone concepts separately. Other entries remain pending, including all ${teaching.nested.topics.xray.pending} nested selections. No radiographs, calibrated projections or paid-lecture access are supplied. Old display/teaching approvals require re-review; earlier topics are preserved through exact authoring transitions.

The [cricothyroid dissection](CRICOTHYROID_DISSECTION.md) adds ${anatomy.nestedDissections.cricothyroidMuscleParts} source-defined muscle parts with ${anatomy.nestedDissections.cricothyroidCartilageLandmarks} optional, nonselectable cartilage landmarks. It reuses the compact selection, cutaway, separation, labels and Undo/Redo controls. The source-preserving derivative explicitly omits ${anatomy.nestedDissections.cricothyroidRemovedArtifactFaces} audited artifact faces; this is disclosed, not clinical approval. Introductory teaching is draft and CT/MRI/US remain pending for these parts. Cartilage is a navigation landmark, not the muscle's tissue parent.

The [biliary and gallbladder relationship view](HEPATIC_BILIARY_RELATIONSHIPS.md) adds ${study.hepaticBiliaryRelationshipPresets} liver study preset using ${study.hepaticBiliaryLandmarks} existing gallbladder/duct landmarks alongside faint liver tissue. Both internal biliary groups remain selectable; landmarks are nonselectable and disappear during separation. Source labels and geometry are unchanged; no common-bile-duct completion, junction validation, scan or surgical model is inferred.

[Component imaging shortcuts](COMPONENT_IMAGING_NAVIGATION.md) connect supported parent organs to existing child CT/MRI/US drafts through a collapsed, source-labelled picker. Opening selects the exact part and its imaging topic in the existing dissection. Pending lessons are omitted; root teaching coverage, scan/lecture entitlements and source geometry remain unchanged. This is local teaching navigation, not patient synchronization or additional clinical coverage.

The [pancreatic duct study](PANCREATIC_DISSECTION.md) separates ${anatomy.nestedDissections.pancreaticDuctSelections} source components with ${anatomy.nestedDissections.pancreaticReferenceSurfaces} optional envelope, preserving all 12,690 retained triangles from ${anatomy.nestedDissections.pancreaticSourceFiles} files. The existing compact controls provide presets, cutaway, separation and draft teaching. It does not infer an accessory duct, validated lumen or scan correspondence. The [root display correction](PANCREATIC_SOURCE_REVIEW.md) and original archives remain intact; old four-source imaging/lecture bindings are not silently mapped to the three-source display. Clinical/device acceptance remains outstanding.

The [optic chiasm and tract study](VISUAL_PATHWAY_DISSECTION.md) adds ${anatomy.nestedDissections.visualPathwayGroups} selectable neural surfaces from ${anatomy.nestedDissections.visualPathwaySourceFiles} source files inside Dissect brain. It opens from below with landmarks off. Across its views, ${anatomy.nestedDissections.visualPathwayContextLandmarks} existing landmarks are available: four posterior landmarks or the pituitary in the [chiasm–pituitary relationship view](VISUAL_PATHWAY_RELATIONSHIPS.md). Shared dissection controls and MRI teaching stay compact. Source seams and relationships still need anatomical review; no complete fibre pathway or patient correspondence is supplied. The original nonpublic prototype remains retained separately.

- ${anatomy.bodyRepresentations} body representations, ${anatomy.bodyBundles} body GLBs, ${anatomy.regions.length} regions plus whole body.
- Dedicated shoulder: ${anatomy.shoulderRepresentations} representations / ${anatomy.shoulderSourceParts} source parts, overlapping the body catalogue.
- Pancreatic dissection: ${anatomy.nestedDissections.pancreaticDuctSelections} selectable duct components and ${anatomy.nestedDissections.pancreaticReferenceSurfaces} optional reference surface. These subdivide the corrected pancreas, not new unique anatomy.
- Nested dissections: ${anatomy.nestedDissections.eyeComponents} eye components, ${anatomy.nestedDissections.ventricularSpaces} ventricular spaces, ${anatomy.nestedDissections.brainstemCompounds} brainstem/cerebellar compounds, ${anatomy.nestedDissections.cerebralSelections} cerebral selections, ${anatomy.nestedDissections.cardiacCavities} cardiac cavities, ${anatomy.nestedDissections.pulmonaryBranchGroups} partial lung branch groups, ${anatomy.nestedDissections.hepaticBranchGroups} liver branch groups, ${anatomy.nestedDissections.renalVascularGroups} renal/adrenal vascular groups and ${anatomy.nestedDissections.visualPathwayGroups} chiasm/tract surfaces. Four superior temporal source parts, seven renal/adrenal groups and three chiasm/tract surfaces add coverage; other nested studies subdivide existing parents. Context reuses existing structures. These are partial source surfaces, not complete organ interiors or clinical approvals. Brief drafts are separate from the root-body inventory below. ${assetsAndRights.publicFileExtensions.glb} public/archive GLBs are retained, including original and alternate display assets. The original catalogue counts remain unchanged.
- ${study.stages} dissection stages and ${study.focuses} focuses. These operate on supplied surfaces; they do not establish complete anatomy.
- Internal studies have optional selected-part original-position guides inside their collapsed separation controls. Guides use the source surface and the exact display displacement; flat plates, cutaways, hidden/context parts and exam mode suppress them. They are display annotations, not anatomical connections. See [scope and checks](ORIGIN_GUIDES.md).
- Find/name identification practice; ${practice.reasoning.concepts} draft reasoning concepts bound to ${practice.reasoning.exactRepresentations} representations in ${practice.reasoning.regions.join(', ')}. One concept per session, without contralateral repetition. See [practice scope and tests](REASONING_PRACTICE.md).
- [Learning-resource contract](LEARNING_RESOURCE_CONTRACT.md): version ${learningIntegration.contractVersion}, ${learningIntegration.supportedKinds.join('/')} anchors; ${learningIntegration.configuredResources} configured resources / ${learningIntegration.configuredCorrespondences} correspondences. Read-only linking infrastructure, not a connected external viewer or publication approval.

## Body teaching readiness

Counts are representations with displayed copy, not unique lessons, complete topic coverage or clinical approvals. Shared source-group copy is counted per representation. The dedicated shoulder retains draft text in its original eight topics; X-ray adds ${teaching.shoulder.xray.specificDraft} draft and ${teaching.shoulder.xray.pending} pending entries. Do not add overlapping representations to claim more unique anatomy.

| Topic | Specific/source-group draft | Identity only | Pending | Generated identification |
| --- | ---: | ---: | ---: | ---: |
${rows}

Quiz-tab notes are separate from interactive practice. [X-ray orientation](XRAY_TEACHING.md) retains three shoulder-bone concepts across six exact body sources and the three overlapping dedicated-shoulder bones; [spinal orientation](SPINE_IMAGING_TEACHING.md) adds 47 exact body sources. Other X-ray topics remain pending. Imaging text is not an acquired-image viewer, segmentation or validated spatial correspondence.

The opt-in [nested learning registry](NESTED_LEARNING_LINKS.md) exposes ${learningIntegration.nestedRepresentations} exact child destinations within ${learningIntegration.availableRepresentations} scope-specific representations. It supports document versions ${learningIntegration.supportedDocumentVersions.join(' and ')}, while the configured production document stays version ${learningIntegration.contractVersion} with no resources. Nested parent/child source and bundle bindings can resolve into the existing dissection routes; this is not a live viewer connection or entitlement.

The ventricular study also has ${study.ventricularRelationshipPresets} [guided relationship presets](VENTRICULAR_RELATIONSHIPS.md), using existing source spaces and context without adding unique anatomy or another panel. Context disappears during separation; pointer handlers do not block selectable structures beneath it. Device acceptance remains pending.

The [cardiac vessel guides](CARDIAC_VESSEL_RELATIONSHIPS.md) add ${study.cardiacRelationshipPresets} chamber–vessel comparisons using ${study.cardiacVesselLandmarks} existing source landmarks. Only the chosen view's vessel surfaces are displayed; one shared source bundle loads on demand. No new mesh files or selectable identities are added. Context is not a connected flow model, validated ostium or valve; clinical/device review remains pending.

The [lung branch study](PULMONARY_DISSECTION.md) separates ${anatomy.nestedDissections.pulmonaryBranchGroups} source-defined groups across two lungs. All ${anatomy.nestedDissections.pulmonarySourceFiles} source files already belonged to the parent lung compounds; none is a separately delineated lobe tissue envelope or fissure. The missing parenchymal surfaces remain a documented gap, not a completed lobe dissection.

## Nested anatomy teaching

The [pancreatic and biliary imaging extension](DUCT_IMAGING_TEACHING.md) supplies three pancreatic CT/MRI/US drafts and one biliary CT draft across four existing source selections. Existing core teaching, quizzes, models, source pins and compact disclosures are unchanged. These are referenced orientation notes, not scans, validated duct communications or automatic access to an imaging atlas or paid lecture.

The [renal venous relationships](RENAL_VENOUS_RELATIONSHIPS.md) add ${study.renalRelationshipPresets} side-specific views through the existing Study view menu, reusing supplied renal/adrenal veins and landmarks. The left adrenal view keeps both veins selectable. Choosing a view is one Undo step; context disappears during separation. No new geometry, connected lumen, flow, clinical approval or resource entitlement is inferred.

The [internal-brain imaging extension](BRAIN_IMAGING_TEACHING.md) adds 14 original CT/MRI drafts across seven existing concepts/eight selections: ventricular spaces, midbrain, pons, medulla and cerebellum. Five primary references cover ventricular assessment and fluid-flow artefacts, posterior-fossa CT limitations and sequence-dependent brainstem MRI detail. Existing identities, core teaching, geometry and access gates are unchanged. Ultrasound and actual scan correspondence remain separate work; clinical/editorial review is pending.

Internal dissection includes [Undo/Redo layers](NESTED_HISTORY.md) across all ten study families. This bounded layer/selection history reuses the compact action row and does not rewind camera, cutaway or separation settings. Device acceptance remains pending.

The [renal vascular study](RENAL_VASCULAR_STUDY.md) adds ${anatomy.nestedDissections.renalVascularGroups} source-labelled vascular groups across ${anatomy.nestedDissections.renalParentViews} kidney views, from ${anatomy.nestedDissections.renalSourceFiles} source files. Optional same-side tissue/vessel context is shown initially and disappears during separation. Renal veins, adrenal vessels and ureteric arterial branches are not a complete circulation or internal kidney tissue. The defective left inferior suprarenal artery remains excluded. [Fourteen shared teaching drafts](RENAL_TEACHING.md) now cover Pathology/CT/MRI, plus ultrasound for ureteric arterial and renal venous groups. Adrenal-vessel ultrasound remains pending; side-specific reference examples do not validate contralateral imaging or any source mesh.

The [pulmonary teaching extension](PULMONARY_TEACHING.md) supplies nine shared Clinical/Pathology/CT drafts for five partial branch groups in the existing collapsed panel. MRI/US remain pending for these groups. No tissue, fissure, disease geometry or scan correspondence is inferred.

The [cerebral teaching extension](CEREBRAL_TEACHING.md) supplies five shared Pathology/CT/MRI drafts across the bilateral insula and anterior superior-temporal fragments. Disease examples explain imaging and regional context, not lesion territories, diagnostic measurements or functional localisation. Specialist review remains required.

The [liver internal-branch study](HEPATIC_DISSECTION.md) exposes ${anatomy.nestedDissections.hepaticBranchGroups} source groups from ${anatomy.nestedDissections.hepaticSourceFiles} existing liver files. Arteries, portal veins, bile ducts and a partial venous tributary have distinct colours and presets. Optional tissue context is nonselectable. Unresolved source VI/VII near-overlap and VIII grouping prevent individual segment labels; no validated Couinaud map or clinical volume is supplied.

Optional pulmonary airway context reuses ${study.pulmonaryAirwayLandmarks} existing trachea/main-bronchus landmarks across ${study.pulmonaryAirwayContexts} per-lung views. It is off by default and absent during separation, with no new model files or nested identities. Main-lung selection now discloses the missing tissue/fissure surfaces. Context is orientation, not validated airway continuity.

The collapsed [Learn more section](NESTED_ANATOMY_TEACHING.md) has ${teaching.nested.concepts} source-pinned concepts across ${teaching.nested.representations} selectable parts, with ${teaching.nested.references} primary-reference links. These counts are separate from the root-body table and overlap parent anatomy. Each part has draft Anatomy, Function and an unscored self-check. Clinical has ${teaching.nested.topics.clinical.specificDraft} draft / ${teaching.nested.topics.clinical.pending} pending; Pathology has ${teaching.nested.topics.pathology.specificDraft} draft / ${teaching.nested.topics.pathology.pending} pending representations. Current authored imaging notes cover CT ${teaching.nested.topics.ct.specificDraft} draft / ${teaching.nested.topics.ct.pending} pending, MRI ${teaching.nested.topics.mri.specificDraft} draft / ${teaching.nested.topics.mri.pending} pending, and ultrasound ${teaching.nested.topics.ultrasound.specificDraft} draft / ${teaching.nested.topics.ultrasound.pending} pending. These are introductory notes, not complete clinical coverage, scans or synchronized viewers. Model-scope self-checks test documented model limitations instead of medical recall. No clinical approvals or external resource access are implied.

The [cardiac chamber study](CARDIAC_CHAMBERS.md) exposes ${anatomy.nestedDissections.cardiacCavities} existing cavity shapes and ${anatomy.nestedDissections.cardiacContextWalls} atrial-wall references. These are spaces and context, not new unique anatomy or a complete dissectible heart. Ambiguous source labels are documented and not admitted to this study.

## Boundaries and next work

- All new teaching and reasoning questions remain drafts requiring independent anatomical, clinical and educator review. Private shoulder review records are not read by this inventory.
- Unresolved teaching identities remain held: FMA45097/FMA45098 (foot sesamoid groups), FMA19728 (pelvic muscle category), FMA61970 (fornical commissure). Source/geometry holds such as unassigned disc FJ3211 remain separate.
- Peripheral nerves/plexuses, complete joint layers, organ interiors, female anatomy and other source gaps remain. Numerical surface counts do not measure completeness.
- The compact interface, device usability, accessibility, label placement and free-orbit explode behaviour still require current browser/device acceptance. Software/SSR tests are not that acceptance.
- The [multimodal integration plan](MULTIMODAL_LEARNING_PLAN.md) distinguishes anatomy-to-resource links from spatial registration. No CT/MRI/X-ray/US viewer or lecture-player connection is implemented by this milestone.
- ${assetsAndRights.dependencyEntries} lockfile entries classified; ${assetsAndRights.unclassifiedDependencies} unclassified. This is not exhaustive legal clearance or a perpetual free-hosting guarantee. BodyParts3D credit/CC BY 4.0 and existing dependency obligations remain; brand rights are reserved. No bundled font binaries or new paid API.
- Saving/publishing and remote GitHub/D-drive recovery are evidenced by dated, verified release checkpoints, not these source counts or a same-PC module snapshot. Conversation history and private review data have separate recovery requirements.

Use [the requirement/acceptance audit](REQUIREMENT_AUDIT.md), [content contract](CONTENT_CONTRACT.md), and [ordered improvement plan](CONTINUOUS_IMPROVEMENT.md) for scope. This summary is not clinical, visual, deployment or legal certification.
`;
}
