"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function AccountDataControls({ existingRequests }: { existingRequests: Array<{ id: string; request_type: string; status: string; detail: string; created_at: string; resolved_at: string | null }> }) {
  const router = useRouter();
  const [requests, setRequests] = useState(existingRequests); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); setError(""); try { const form = new FormData(event.currentTarget); const response = await fetch("/api/learner/data", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const result = await response.json() as { request?: { id: string; status: string }; requests?: typeof existingRequests; error?: string }; if (!response.ok) throw new Error(result.error ?? "The request could not be recorded."); setRequests(result.requests ?? requests); setMessage(`Account request ${result.request?.id.slice(0, 8).toUpperCase()} recorded for manual review.`); event.currentTarget.reset(); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "The request could not be recorded."); } finally { setBusy(false); } }
  return <div className="account-data-controls"><section><p className="section-index">Portable copy</p><h2>Export your education record</h2><p>Download the profile, enrolment, progress, notes, review queue and completion information associated with this education account.</p><a className="primary-button" href="/api/learner/data">Download JSON export <span>→</span></a></section><section><p className="section-index">Learner rights request</p><h2>Request correction, restriction or deletion</h2><p>Requests are queued for accountable review. Deletion is never performed immediately because assessment, audit or contractual retention may first require a documented decision.</p><form className="studio-form" onSubmit={submit}><label><span>Request type</span><select name="requestType"><option value="correction">Correct account data</option><option value="restriction">Restrict processing</option><option value="deletion">Delete education account</option></select></label><label><span>Details</span><textarea name="detail" placeholder="Describe the request. Do not include patient information." /></label>{(message || error) && <p className={error ? "form-error" : "studio-form-message"} role={error ? "alert" : "status"}>{error || message}</p>}<button disabled={busy}>{busy ? "Recording…" : "Record request"}</button></form></section><section className="account-request-ledger"><p className="section-index">Request history</p><h2>Reviewable account actions</h2>{requests.length ? requests.map((request) => <article key={request.id}><span>{request.request_type}</span><b>{request.status}</b><p>{request.detail || "No additional detail supplied."}</p><small>{new Date(request.created_at).toLocaleString("en-GB")}</small></article>) : <p className="empty-control">No learner-rights requests have been recorded.</p>}</section></div>;
}
