"use client";

import { FormEvent, useState } from "react";

type Snapshot = {
  organization: { name: string };
  entitlement: { learnerLimit: number; educatorLimit: number };
  members: Array<{ userId: string; displayName: string; email: string; role: string; status: string; joinedAt: string; lastSeenAt: string }>;
  invitations: Array<{ id: string; email: string; role: string; status: string; createdAt: string; expiresAt: string; acceptedAt: string | null }>;
  outbox: Record<string, number>;
};

export function InstitutionPeopleManager({ initialSnapshot }: { initialSnapshot: Snapshot }) {
  const [snapshot, setSnapshot] = useState(initialSnapshot); const [links, setLinks] = useState<Array<{ email: string; role: string; invitationPath: string; emailDelivery: string }>>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); setLinks([]); try { const form = new FormData(event.currentTarget); const response = await fetch("/api/platform/people", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "invite", roster: form.get("roster"), validDays: Number(form.get("validDays")) }) }); const result = await response.json() as { snapshot?: Snapshot; created?: Array<{ email: string; role: string; invitationPath: string; emailDelivery: string }>; error?: string }; if (!response.ok || !result.snapshot) throw new Error(result.error ?? "Invitations could not be created."); setSnapshot(result.snapshot); setLinks(result.created ?? []); event.currentTarget.reset(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Invitations could not be created."); } finally { setBusy(false); } }
  const learners = snapshot.members.filter((member) => member.role === "learner").length; const educators = snapshot.members.filter((member) => member.role !== "learner").length;
  return <div className="people-manager"><section className="people-metrics"><article><span>Active learners</span><b>{learners} / {snapshot.entitlement.learnerLimit}</b></article><article><span>Educators and admins</span><b>{educators} / {snapshot.entitlement.educatorLimit}</b></article><article><span>Pending invitations</span><b>{snapshot.invitations.filter((item) => item.status === "pending").length}</b></article><article><span>Email outbox</span><b>{snapshot.outbox.sent ?? 0} sent · {snapshot.outbox.held ?? 0} held</b></article></section><section className="people-grid"><div><p className="section-index">Roster</p><h2>Current organisation members</h2><div className="people-table"><header><span>Person</span><span>Role</span><span>Status</span><span>Last seen</span></header>{snapshot.members.map((member) => <div key={member.userId}><span><b>{member.displayName}</b><small>{member.email}</small></span><span>{member.role}</span><span>{member.status}</span><span>{new Date(member.lastSeenAt).toLocaleDateString("en-GB")}</span></div>)}</div></div><aside><p className="section-index">Invite or import</p><h2>Add a bounded roster.</h2><p>Paste one <code>email,role</code> pair per line. Approved roles are learner, educator, reviewer and administrator.</p><form className="studio-form" onSubmit={submit}><label><span>Roster rows</span><textarea name="roster" required placeholder={"learner@example.edu,learner\neducator@example.edu,educator"} /></label><label><span>Invitation validity</span><select name="validDays" defaultValue="14"><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label>{error && <p className="form-error" role="alert">{error}</p>}<button disabled={busy}>{busy ? "Creating…" : "Create invitations"}</button></form>{links.length > 0 && <div className="invitation-handoff" role="status"><span>Invitation handoff</span><p>Copy held or failed-delivery links now. Sent invitations can still be copied for support.</p>{links.map((item) => <label key={item.email}><b>{item.email} · {item.role} · email {item.emailDelivery}</b><input readOnly value={item.invitationPath} onFocus={(event) => event.currentTarget.select()} /></label>)}</div>}</aside></section><section className="invitation-ledger"><header><div><p className="section-index">Invitation ledger</p><h2>Pending and completed access invitations</h2></div><p>Tokens are never stored in readable form. Reissuing an invitation supersedes the previous pending link.</p></header>{snapshot.invitations.map((item) => <article key={item.id}><span>{item.email}</span><b>{item.role}</b><span>{item.status}</span><small>Expires {new Date(item.expiresAt).toLocaleDateString("en-GB")}</small></article>)}</section></div>;
}
