"use client";

import { FormEvent, useState } from "react";

type Preferences = { courseUpdates: boolean; assignmentReminders: boolean; reviewReminders: boolean; productUpdates: boolean; deliveryMode: string; updatedAt: string | null };
export function NotificationPreferences({ initialPreferences }: { initialPreferences: Preferences }) {
  const [preferences, setPreferences] = useState(initialPreferences); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); setError(""); try { const form = new FormData(event.currentTarget); const response = await fetch("/api/learner/preferences", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ courseUpdates: form.get("courseUpdates") === "on", assignmentReminders: form.get("assignmentReminders") === "on", reviewReminders: form.get("reviewReminders") === "on", productUpdates: form.get("productUpdates") === "on" }) }); const body = await response.json() as Preferences & { error?: string }; if (!response.ok) throw new Error(body.error ?? "Preferences could not be saved."); setPreferences(body); setMessage("Notification preferences saved."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Preferences could not be saved."); } finally { setBusy(false); } }
  return <section className="notification-preferences" id="notifications"><p className="section-index">Notifications</p><h2>Choose useful education reminders.</h2><p>Email delivery remains disabled during the non-live phase. These preferences currently control future and in-app notification eligibility only.</p><form onSubmit={submit}>{[["courseUpdates", "Course updates", "New releases and material changes"], ["assignmentReminders", "Assignment reminders", "Available, due and expiring workbooks"], ["reviewReminders", "Spaced-review reminders", "Items due in your review queue"], ["productUpdates", "Product updates", "Optional Visible Medicine platform news"]].map(([name, label, description]) => <label key={name}><input type="checkbox" name={name} defaultChecked={preferences[name as keyof Preferences] === true} /><span><b>{label}</b>{description}</span></label>)}{(message || error) && <p className={error ? "form-error" : "studio-form-message"} role={error ? "alert" : "status"}>{error || message}</p>}<button disabled={busy}>{busy ? "Saving…" : "Save notification preferences"}</button></form><small>Delivery mode: {preferences.deliveryMode.replaceAll("-", " ")}</small></section>;
}
