/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.review-local.jsonc --include-runtime=false` (hash: aafd7c65c3c1d839dcb66f4211d91eaa)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./node_modules/vinext/dist/server/fetch-handler");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
