import type { ContentTab } from '../app/anatomy-data';
import type { BodyStructure } from '../app/body-types';
import type { ContentLesson } from './content-types';
import type { ShoulderClinicalGroup } from './shoulder-clinical-curriculum';

export interface ForearmClinicalGroup extends Omit<
  ShoulderClinicalGroup,
  'identities'
> {
  identities: readonly (readonly [
    fmaId: string,
    side: string,
    files: readonly string[],
  ])[];
}
const books = 'https://www.ncbi.nlm.nih.gov/books/';
const pubmed = 'https://pubmed.ncbi.nlm.nih.gov/';
const aaos = 'https://www.orthoinfo.org/diseases--conditions/';
const ain = books + 'NBK525956/';
const pin = books + 'NBK541046/';
const surface =
  'Reference muscle surface only; no tear, inflamed sheath, compressed nerve or patient scan is represented.';

/** Original factual drafts. File arrays are explicit official memberships,
 * including both ECU/FDS components; no side is generated by mirroring. */
export const forearmClinicalGroups: readonly ForearmClinicalGroup[] = [
  {
    key: 'ecu',
    identities: [
      ['FMA38507', 'right', ['FJ1472', 'FJ1517']],
      ['FMA38508', 'left', ['FJ1472M', 'FJ1517M']],
    ],
    scope:
      'Two source components stay grouped. The tendon groove and stabilising subsheath are not independently validated.',
    pathology: {
      body: 'ECU tendon instability is one possible cause of pain on the ulnar side of the wrist.',
      bullets: [
        'Movement of the tendon beyond the groove can also occur in asymptomatic wrists; displacement alone is not a diagnosis.',
      ],
    },
    clinical: {
      body: 'Relate symptoms to wrist position and tendon behaviour, while considering other causes of ulnar-sided pain.',
      bullets: [
        'A small ultrasound study described normal excursion in 20 asymptomatic wrists. Its measurements are not universal diagnostic cut-offs.',
        'The explode control separates reference structures for learning; it does not simulate ECU instability.',
      ],
    },
    references: [pubmed + '15810097/'],
  },
  {
    key: 'fds',
    identities: [
      ['FMA38470', 'right', ['FJ1475', 'FJ1499']],
      ['FMA38471', 'left', ['FJ1475M', 'FJ1499M']],
    ],
    scope:
      'This selection combines two source components, not independently selectable or validated digital tendon slips.',
    pathology: {
      body: 'A cut or tear involving a finger flexor tendon can impair bending. Partial tendon injuries may still permit movement.',
      bullets: [
        'Distinguish superficialis attachment to the middle phalanx from profundus attachment to the distal phalanx.',
      ],
    },
    clinical: {
      body: 'Assessment identifies which finger joints and tendons are affected and checks for accompanying nerve or vascular injury.',
      bullets: [
        'Superficialis principally flexes the proximal interphalangeal joint; it is not the distal fingertip flexor.',
        'Preserved movement does not exclude a partial injury. A suspected tendon injury, especially after a cut, warrants prompt clinical assessment.',
      ],
    },
    references: [aaos + 'flexor-tendon-injuries/', books + 'NBK539723/'],
  },
  {
    key: 'first-compartment',
    identities: [
      ['FMA38516', 'right', ['FJ1484']],
      ['FMA38517', 'left', ['FJ1484M']],
      ['FMA38519', 'right', ['FJ1494']],
      ['FMA38520', 'left', ['FJ1494M']],
    ],
    scope:
      'APL and EPB share this compartment-level teaching. Accessory slips, septa and sheath thickening are not mapped.',
    pathology: {
      body: 'De Quervain’s tenosynovitis affects the APL and EPB tendons at the thumb side of the wrist, with impaired gliding in their sheath.',
      bullets: [
        'Pain may increase with gripping, lifting or thumb movement; swelling can occur.',
        'This is not the EPL tendon or median-nerve compression in the carpal tunnel.',
      ],
    },
    clinical: {
      body: 'Use the first dorsal compartment relationship to understand the location of symptoms, not to diagnose from pain alone.',
      bullets: [
        'History and examination distinguish this condition from other radial-sided wrist problems.',
        'APL acts mainly at the thumb base; EPB mainly extends its knuckle. Shared disease context does not make their actions identical.',
      ],
    },
    references: [
      aaos + 'de-quervains-tendinosis/',
      'https://anatomy.ttuhscep.edu/anatomytables/muscles_upperlimb.html',
    ],
  },
  {
    key: 'brachioradialis',
    identities: [
      ['FMA38486', 'right', ['FJ1487']],
      ['FMA38487', 'left', ['FJ1487M']],
    ],
    scope: surface,
    pathology: {
      body: 'Radial nerve dysfunction may weaken brachioradialis when the lesion affects its motor supply.',
      bullets: [
        'Nearby superficial radial nerve irritation is sensory, not brachioradialis motor palsy.',
      ],
    },
    clinical: {
      body: 'Elbow-flexion strength contributes to neurological assessment alongside other muscles, reflexes and sensation.',
      bullets: [
        'Brachioradialis receives a radial branch proximal to the posterior interosseous nerve; isolated PIN dysfunction should not be equated with its weakness.',
        'It attaches to the radius and does not cross the wrist.',
      ],
    },
    references: [books + 'NBK526110/', pin],
  },
  {
    key: 'ecrb',
    identities: [
      ['FMA38498', 'right', ['FJ1489']],
      ['FMA38499', 'left', ['FJ1489M']],
    ],
    scope: surface,
    pathology: {
      body: 'Lateral epicondylitis, often called tennis elbow, commonly involves the proximal ECRB tendon and degenerative or microscopic tearing changes.',
      bullets: [
        'It also occurs outside racquet sports. Repeated loading at work or during other activities can contribute.',
      ],
    },
    clinical: {
      body: 'Pain near the lateral epicondyle during gripping or wrist loading is relevant, but does not identify a tendon lesion by itself.',
      bullets: [
        'Distinguish local tendon pain from neurological weakness and other elbow disorders.',
        'ECRB and ECRL are separate muscles with different proximal and distal attachments; this is not a diagnosis applied to every wrist extensor.',
      ],
    },
    references: [
      aaos + 'tennis-elbow-lateral-epicondylitis/',
      books + 'NBK539719/',
    ],
  },
  {
    key: 'ecrl',
    identities: [
      ['FMA38495', 'right', ['FJ1490']],
      ['FMA38496', 'left', ['FJ1490M']],
    ],
    scope: surface,
    pathology: {
      body: 'The pattern of wrist and finger weakness helps distinguish a proximal radial nerve lesion from posterior interosseous dysfunction.',
      bullets: [
        'ECRL can preserve wrist extension in an isolated PIN lesion, sometimes with radial deviation.',
      ],
    },
    clinical: {
      body: 'Preserved wrist extension does not establish normal function of all finger extensors.',
      bullets: [
        'Interpret the pattern with sensation and other muscles, not a single movement.',
        'Selecting ECRL does not reproduce a nerve lesion or establish its level.',
      ],
    },
    references: [pin],
  },
  {
    key: 'digital-extensors',
    identities: [
      ['FMA38504', 'right', ['FJ1491']],
      ['FMA38505', 'left', ['FJ1491M']],
      ['FMA38501', 'right', ['FJ1492']],
      ['FMA38502', 'left', ['FJ1492M']],
      ['FMA38525', 'right', ['FJ1493']],
      ['FMA38526', 'left', ['FJ1493M']],
    ],
    scope:
      'ED, EDM and EI share this overview; individual tendon connections and the extensor apparatus are not separately validated.',
    pathology: {
      body: 'Extensor tendon injury can impair finger straightening. Superficial tendons on the back of the hand are vulnerable to cuts.',
      bullets: [
        'The level matters: terminal tendon injury may cause mallet finger, while central-slip injury can produce a different joint pattern.',
        'Failure to extend can also reflect motor nerve dysfunction without tendon rupture.',
      ],
    },
    clinical: {
      body: 'Identify the affected digit and joint rather than calling every extension deficit a mallet finger.',
      bullets: [
        'ED serves multiple fingers; EDM adds little-finger extension and EI adds index extension.',
        'Wounds and new loss of movement require clinical assessment. The surface cannot determine tendon continuity or nerve function.',
      ],
    },
    references: [
      'https://assh.my.site.com/handcare/condition/extensor-tendon-injury',
      pin,
      books + 'NBK534805/',
    ],
  },
  {
    key: 'epl',
    identities: [
      ['FMA38522', 'right', ['FJ1495']],
      ['FMA38523', 'left', ['FJ1495M']],
    ],
    scope: surface,
    pathology: {
      body: 'EPL tendon rupture can occur after a wrist fracture, including a minimally displaced fracture, or in association with rheumatoid disease.',
      bullets: [
        'Loss of active thumb-tip extension is different from pain involving APL and EPB in de Quervain’s.',
      ],
    },
    clinical: {
      body: 'EPL reaches the distal thumb phalanx and extends its interphalangeal joint; EPB has a more proximal attachment.',
      bullets: [
        'A new inability to straighten the thumb tip merits assessment of tendon continuity and motor function.',
        'No rupture site, tendon retraction or patient-specific surgical plan is supplied here.',
      ],
    },
    references: [
      'https://www.bssh.ac.uk/patients/conditions/30/thumb_extensor_tendon_epl_rupture',
      books + 'NBK544294/',
    ],
  },
  {
    key: 'fcr',
    identities: [
      ['FMA38460', 'right', ['FJ1496']],
      ['FMA38461', 'left', ['FJ1496M']],
    ],
    scope: surface,
    pathology: {
      body: 'FCR tendinitis is an uncommon reported cause of pain on the palmar, thumb-side aspect of the wrist.',
      bullets: [
        'Tendon involvement must be distinguished from other causes of pain in this region.',
      ],
    },
    clinical: {
      body: 'Relate the painful region to the wrist-flexor tendon, while evaluating alternative joint, bone and nerve causes.',
      bullets: [
        'A small retrospective case series is not a universal management guideline.',
        'The atlas does not estimate tendon damage, prescribe imaging thresholds or select treatment.',
      ],
    },
    references: [pubmed + '39166186/'],
  },
  {
    key: 'fdp',
    identities: [
      ['FMA38479', 'right', ['FJ1497']],
      ['FMA38480', 'left', ['FJ1497M']],
    ],
    scope:
      'The muscle remains grouped; individual finger tendons and motor territories are not segmented.',
    pathology: {
      body: 'Avulsion of a distal FDP tendon, often called jersey finger, disconnects the fingertip flexor from its bony attachment.',
      bullets: [
        'Weak fingertip flexion can also have a neurological cause; tendon avulsion and denervation are different mechanisms.',
      ],
    },
    clinical: {
      body: 'Distal interphalangeal flexion relates to FDP, not the middle-phalanx attachment of FDS.',
      bullets: [
        'Typical supply is anterior interosseous for digits 2–3 and ulnar for 4–5, with variation; do not label the entire muscle as an AIN territory.',
        'A sudden loss of fingertip flexion after injury warrants prompt assessment.',
      ],
    },
    references: [
      'https://www.assh.org/handcareprod/servlet/servlet.FileDownload?file=00P0a00000obXL3EAM',
      books + 'NBK526046/',
      aaos + 'flexor-tendon-injuries/',
    ],
  },
  {
    key: 'fpl',
    identities: [
      ['FMA38482', 'right', ['FJ1498']],
      ['FMA38484', 'left', ['FJ1498M']],
    ],
    scope: surface,
    pathology: {
      body: 'Weak thumb-tip flexion may result from FPL tendon injury or anterior interosseous nerve dysfunction.',
      bullets: [
        'AIN syndrome is motor-only; inflammatory neuropathy is an important cause, so it should not automatically be called mechanical entrapment.',
      ],
    },
    clinical: {
      body: 'Altered thumb–index pinch is a clue, not a stand-alone diagnosis.',
      bullets: [
        'Assessment distinguishes tendon continuity from a motor pattern involving FPL, radial FDP and pronator quadratus.',
        'Sensory loss suggests additional or alternative involvement rather than isolated AIN dysfunction.',
      ],
    },
    references: [ain, aaos + 'flexor-tendon-injuries/'],
  },
  {
    key: 'palmaris',
    identities: [
      ['FMA38463', 'right', ['FJ1502']],
      ['FMA38464', 'left', ['FJ1502M']],
    ],
    scope:
      'The reference includes palmaris longus; its presence, shape and relationship to nerves are not universal.',
    pathology: {
      body: 'Congenital absence of palmaris longus is a normal variant, not evidence of rupture or disease.',
      bullets: [
        'Unusual muscle forms can occasionally contribute to local nerve compression or resemble a soft-tissue mass.',
      ],
    },
    clinical: {
      body: 'Confirm individual anatomy when interpreting a wrist prominence or considering this tendon as a graft source.',
      bullets: [
        'Its limited wrist-flexion contribution does not make it interchangeable with adjacent tendons or the median nerve.',
        'The atlas does not establish graft suitability or provide harvesting instructions.',
      ],
    },
    references: [books + 'NBK519516/'],
  },
  {
    key: 'quadratus',
    identities: [
      ['FMA38454', 'right', ['FJ1503']],
      ['FMA38455', 'left', ['FJ1503M']],
    ],
    scope: surface,
    pathology: {
      body: 'Pronator quadratus can be affected in anterior interosseous neuropathy, alongside FPL and the radial FDP contribution.',
      bullets: [
        'A muscle surface is not evidence of denervation or its cause.',
      ],
    },
    clinical: {
      body: 'Pronation also uses pronator teres, so remaining pronation does not exclude quadratus weakness.',
      bullets: [
        'Interpret this deep muscle within the wider motor pattern; suspected neuropathy may require electrodiagnostic assessment.',
        'No muscle-strength measurement or patient motor map is included.',
      ],
    },
    references: [ain, books + 'NBK539784/'],
  },
  {
    key: 'supinator',
    identities: [
      ['FMA38513', 'right', ['FJ1505']],
      ['FMA38514', 'left', ['FJ1505M']],
    ],
    scope:
      'The arcade of Frohse and nerve passage are teaching relationships, not validated compression geometry.',
    pathology: {
      body: 'The deep radial nerve passes through the supinator region, where compression can affect downstream extensor function.',
      bullets: [
        'Pain-dominant radial tunnel syndrome is distinguished from PIN motor palsy.',
      ],
    },
    clinical: {
      body: 'Do not equate lateral forearm pain with paralysis of the finger extensors.',
      bullets: [
        'The history and motor pattern help distinguish nerve dysfunction from tendon or joint problems.',
        'Exploding the muscle does not decompress a modelled nerve or reproduce a clinical test.',
      ],
    },
    references: [pin, books + 'NBK580564/'],
  },
  {
    key: 'pronator-teres',
    identities: [
      ['FMA38560', 'right', ['FJ1474']],
      ['FMA38561', 'left', ['FJ1474M']],
      ['FMA38562', 'right', ['FJ1516']],
      ['FMA38563', 'left', ['FJ1516M']],
    ],
    scope:
      'Both separately selectable heads share whole-muscle clinical context, not independently localised lesions.',
    pathology: {
      body: 'Proximal median nerve compression in the pronator region can cause forearm pain and variable sensory or motor symptoms.',
      bullets: [
        'The syndrome is not the same as isolated AIN dysfunction or median compression at the wrist.',
      ],
    },
    clinical: {
      body: 'Assess the distribution of symptoms, including the palm, together with the broader nerve and muscle pattern.',
      bullets: [
        'Pronator teres itself may be spared when its motor branch leaves proximal to the compression.',
        'A selected humeral or ulnar head does not prove the level or cause of a neuropathy.',
      ],
    },
    references: [books + 'NBK526090/'],
  },
  {
    key: 'fcu',
    identities: [
      ['FMA38617', 'right', ['FJ1473']],
      ['FMA38618', 'left', ['FJ1473M']],
      ['FMA38619', 'right', ['FJ1518']],
      ['FMA38620', 'left', ['FJ1518M']],
    ],
    scope:
      'Humeral and ulnar heads share this whole-muscle overview. No separate head-specific neuropathy or validated nerve tunnel is represented.',
    pathology: {
      body: 'The ulnar nerve enters the forearm between the FCU heads; this relationship matters in proximal ulnar nerve compression.',
      bullets: [
        'A nearby muscle is not necessarily the cause of compression, and regional pain alone does not establish neuropathy.',
      ],
    },
    clinical: {
      body: 'Consider wrist-flexion and ulnar-deviation function together with other ulnar-innervated muscles and sensation.',
      bullets: [
        'The two heads contribute to one shared FCU tendon and are not independent clinical tests.',
        'A nerve lesion at the wrist lies distal to the forearm motor branches; localisation requires the whole pattern, not this muscle alone.',
      ],
    },
    references: [books + 'NBK526051/'],
  },
];

const byFma = new Map(
  forearmClinicalGroups.flatMap((group) =>
    group.identities.map(
      (identity) => [identity[0], { group, identity }] as const,
    ),
  ),
);
export function forearmClinicalLesson(
  s: BodyStructure,
  tab: ContentTab,
): ContentLesson | undefined {
  if (
    (tab !== 'pathology' && tab !== 'clinical') ||
    s.system !== 'muscles' ||
    s.category !== 'muscle' ||
    s.region !== 'forearm' ||
    s.regions.length !== 1 ||
    s.regions[0] !== 'forearm' ||
    s.sourceTree !== 'isa'
  )
    return undefined;
  const match = byFma.get(s.fmaId);
  if (
    !match ||
    s.laterality !== match.identity[1] ||
    s.sources.length !== match.identity[2].length ||
    s.sources.some((p, i) => p.file !== match.identity[2][i])
  )
    return undefined;
  const { group } = match,
    topic = group[tab];
  return {
    readiness: 'draft',
    title: `${s.name} · ${tab === 'pathology' ? 'Injury & disease' : 'Clinical context'} · draft`,
    body: topic.body,
    bullets: [...topic.bullets, group.scope],
    note: [
      'Draft teaching; independent anatomical and clinical review pending. Educational context, not a patient diagnosis or treatment plan.',
      s.coverageNote,
    ]
      .filter(Boolean)
      .join(' '),
    citations: [...group.references],
  };
}
