import type { ContentTab } from '../app/anatomy-data';
import type { BodyStructure } from '../app/body-types';
import type { ContentLesson } from './content-types';

type ThoracicOrganClinicalIdentity = readonly [
  fma: string,
  side: string,
  tree: 'isa' | 'partof',
  files: readonly string[],
  region: string,
  regions: readonly string[],
  category: 'organ',
];
interface ThoracicOrganClinicalGroup {
  key: string;
  identities: readonly ThoracicOrganClinicalIdentity[];
  scope: string;
  pathology: { body: string; bullets: readonly string[] };
  clinical: { body: string; bullets: readonly string[] };
  references: readonly string[];
}
/** Short original drafts; exact source identities, not inferred mirror copies. */
export const thoracicOrganClinicalGroups: readonly ThoracicOrganClinicalGroup[] =
  [
    {
      key: 'heart',
      identities: [
        [
          'FMA7088',
          'unpaired',
          'partof',
          [
            'FJ2417',
            'FJ2418',
            'FJ2419',
            'FJ2420',
            'FJ2421',
            'FJ2422',
            'FJ2423',
            'FJ2424',
            'FJ2425',
            'FJ2426',
            'FJ2427',
            'FJ2429',
            'FJ2430',
            'FJ2431',
            'FJ2432',
            'FJ2433',
            'FJ2434',
            'FJ2435',
            'FJ2436',
            'FJ2437',
            'FJ2438',
            'FJ2439',
            'FJ2655',
            'FJ2667',
            'FJ2668',
            'FJ2670',
            'FJ2671',
            'FJ2672',
            'FJ2673',
            'FJ2674',
            'FJ2675',
            'FJ2676',
            'FJ2677',
            'FJ2692',
            'FJ2693',
            'FJ2694',
            'FJ2695',
            'FJ2696',
            'FJ2697',
            'FJ2698',
            'FJ2699',
            'FJ2700',
            'FJ2714',
            'FJ2715',
            'FJ2716',
            'FJ2717',
            'FJ2718',
            'FJ2719',
            'FJ2720',
            'FJ2721',
            'FJ2722',
            'FJ2724',
            'FJ2727',
            'FJ2728',
            'FJ2729',
            'FJ2731',
          ],
          'thorax',
          ['thorax'],
          'organ',
        ],
      ],
      scope:
        'One 56-component heart aggregate; 27 official PART-OF components belong to five separately selectable coronary vessel groups. Chambers, valves, perfusion, conduction and contraction are not independently validated.',
      pathology: {
        body: 'Myocardial infarction is injury and death of heart muscle after inadequate blood supply. Coronary plaque disruption with clot formation is a common mechanism, but not every infarction involves an obstructive coronary plaque.',
        bullets: [
          "Heart failure concerns inadequate filling or pumping for the body's needs; it does not mean the heart has stopped. A heart attack and cardiac arrest are also different events.",
          'A reference surface cannot establish ischaemia, infarct extent, ejection fraction or an abnormal rhythm.',
        ],
      },
      clinical: {
        body: "Relate the heart muscle to its coronary supply without treating a selected vessel or coloured surface as a map of a patient's infarction. Clinical assessment, ECG and blood tests provide evidence that this static model cannot.",
        bullets: [
          'Chest pressure or squeezing, spreading pain and breathlessness can be warning signs; indigestion-like discomfort can also occur.',
          'In the UK, call 999 for suspected heart attack or severe breathing difficulty. Do not delay help to inspect the atlas.',
        ],
      },
      references: [
        'https://www.nhlbi.nih.gov/health/heart-attack/causes',
        'https://www.nhlbi.nih.gov/health/heart-failure',
        'https://www.nhs.uk/conditions/heart-attack/',
      ],
    },
    {
      key: 'lungs',
      identities: [
        [
          'FMA7309',
          'right',
          'partof',
          [
            'FJ2041',
            'FJ2044',
            'FJ2449',
            'FJ2451',
            'FJ2452',
            'FJ2453',
            'FJ2454',
            'FJ2455',
            'FJ2456',
            'FJ2457',
            'FJ2458',
            'FJ2459',
            'FJ2470',
            'FJ2481',
            'FJ2486',
            'FJ2487',
            'FJ2488',
            'FJ2489',
            'FJ2490',
            'FJ2491',
            'FJ2492',
            'FJ2493',
            'FJ2494',
            'FJ2495',
            'FJ2496',
            'FJ2497',
            'FJ2498',
            'FJ2499',
            'FJ2500',
            'FJ2501',
            'FJ2502',
            'FJ2503',
            'FJ2504',
            'FJ2505',
            'FJ2506',
            'FJ2507',
            'FJ2508',
            'FJ2509',
            'FJ2510',
            'FJ2511',
            'FJ2512',
            'FJ2513',
            'FJ2514',
            'FJ2515',
            'FJ2516',
            'FJ2517',
            'FJ2518',
            'FJ2519',
            'FJ2520',
            'FJ2521',
            'FJ2522',
            'FJ2523',
            'FJ2524',
            'FJ2525',
            'FJ2526',
            'FJ2967',
            'FJ2968',
            'FJ2969',
            'FJ2970',
            'FJ2971',
            'FJ2972',
            'FJ2973',
            'FJ2974',
            'FJ2975',
            'FJ2976',
            'FJ2977',
            'FJ2978',
            'FJ2979',
            'FJ2980',
            'FJ2981',
            'FJ2982',
            'FJ2983',
            'FJ2984',
            'FJ2985',
            'FJ2986',
            'FJ2987',
            'FJ2988',
            'FJ2989',
            'FJ2990',
            'FJ2991',
            'FJ2992',
            'FJ2993',
            'FJ2994',
            'FJ2995',
            'FJ2996',
            'FJ2997',
            'FJ2998',
            'FJ2999',
            'FJ3000',
            'FJ3001',
            'FJ3002',
            'FJ3003',
            'FJ3004',
            'FJ3005',
            'FJ3006',
            'FJ3007',
            'FJ3008',
            'FJ3009',
            'FJ3010',
            'FJ3011',
            'FJ3012',
            'FJ3013',
            'FJ3014',
            'FJ3015',
            'FJ3016',
            'FJ3017',
            'FJ3018',
            'FJ3021',
            'FJ3022',
            'FJ3023',
            'FJ3024',
            'FJ3025',
            'FJ3026',
            'FJ3027',
            'FJ3028',
            'FJ3029',
            'FJ3030',
            'FJ3031',
            'FJ3032',
            'FJ3033',
            'FJ3034',
            'FJ3035',
            'FJ3036',
            'FJ3037',
            'FJ3038',
            'FJ3039',
            'FJ3041',
            'FJ3042',
            'FJ3043',
            'FJ3044',
            'FJ3045',
            'FJ3046',
            'FJ3047',
            'FJ3048',
            'FJ3049',
            'FJ3050',
            'FJ3051',
            'FJ3052',
            'FJ3053',
            'FJ3054',
            'FJ3055',
            'FJ3056',
            'FJ3057',
            'FJ3058',
            'FJ3059',
            'FJ3060',
            'FJ3061',
            'FJ3062',
            'FJ3063',
            'FJ3064',
            'FJ3065',
            'FJ3066',
            'FJ3067',
            'FJ3068',
            'FJ3069',
            'FJ3070',
          ],
          'thorax',
          ['thorax'],
          'organ',
        ],
        [
          'FMA7310',
          'left',
          'partof',
          [
            'FJ2441',
            'FJ2442',
            'FJ2443',
            'FJ2444',
            'FJ2445',
            'FJ2446',
            'FJ2447',
            'FJ2448',
            'FJ2460',
            'FJ2461',
            'FJ2462',
            'FJ2463',
            'FJ2464',
            'FJ2465',
            'FJ2466',
            'FJ2467',
            'FJ2468',
            'FJ2469',
            'FJ2471',
            'FJ2472',
            'FJ2473',
            'FJ2474',
            'FJ2475',
            'FJ2476',
            'FJ2477',
            'FJ2478',
            'FJ2479',
            'FJ2480',
            'FJ2482',
            'FJ2483',
            'FJ2484',
            'FJ2485',
            'FJ2527',
            'FJ2528',
            'FJ2529',
            'FJ2530',
            'FJ2531',
            'FJ2532',
            'FJ2533',
            'FJ2534',
            'FJ2535',
            'FJ2536',
            'FJ2537',
            'FJ2538',
            'FJ2540',
            'FJ2881',
            'FJ2882',
            'FJ2883',
            'FJ2884',
            'FJ2885',
            'FJ2886',
            'FJ2887',
            'FJ2888',
            'FJ2889',
            'FJ2890',
            'FJ2891',
            'FJ2892',
            'FJ2893',
            'FJ2894',
            'FJ2895',
            'FJ2896',
            'FJ2897',
            'FJ2898',
            'FJ2899',
            'FJ2900',
            'FJ2901',
            'FJ2902',
            'FJ2903',
            'FJ2904',
            'FJ2905',
            'FJ2906',
            'FJ2907',
            'FJ2908',
            'FJ2909',
            'FJ2910',
            'FJ2911',
            'FJ2912',
            'FJ2913',
            'FJ2914',
            'FJ2915',
            'FJ2916',
            'FJ2917',
            'FJ2918',
            'FJ2919',
            'FJ2920',
            'FJ2921',
            'FJ2922',
            'FJ2923',
            'FJ2926',
            'FJ2927',
            'FJ2928',
            'FJ2929',
            'FJ2930',
            'FJ2931',
            'FJ2932',
            'FJ2934',
            'FJ2935',
            'FJ2936',
            'FJ2937',
            'FJ2938',
            'FJ2939',
            'FJ2940',
            'FJ2941',
            'FJ2942',
            'FJ2943',
            'FJ2945',
            'FJ2946',
            'FJ2947',
            'FJ2948',
            'FJ2949',
            'FJ2951',
            'FJ2952',
            'FJ2953',
            'FJ2954',
            'FJ2956',
            'FJ2957',
            'FJ2958',
            'FJ2959',
            'FJ2960',
            'FJ2961',
            'FJ2962',
            'FJ2963',
            'FJ2964',
            'FJ2965',
          ],
          'thorax',
          ['thorax'],
          'organ',
        ],
      ],
      scope:
        'Each lung remains a grouped source selection: 156 right and 124 left components. File count is not a count of validated lobes, bronchopulmonary segments or microscopic air sacs. No infection, pleural fluid or ventilation is simulated.',
      pathology: {
        body: 'Pneumonia is an infection of one or both lungs. Inflammation can replace air within the alveoli with fluid or pus, impairing breathing; bacteria, viruses and fungi are possible causes.',
        bullets: [
          'A whole-lung highlight does not show the distribution of pneumonia or identify its organism.',
          'Keep alveolar disease distinct from material in the pleural space outside the lung; clipping a lung surface does not expose either as real tissue.',
        ],
      },
      clinical: {
        body: 'Cough, fever and breathing difficulty may occur, with severity influenced by age and health. Compare the clinical examination with actual imaging and other investigations; model colour, transparency and shape cannot diagnose infection.',
        bullets: [
          "Use the right/left and lobar relationships in Anatomy to orient study, not to infer a patient's diseased side.",
          'In the UK, severe breathing difficulty such as gasping or being unable to speak requires emergency help via 999.',
        ],
      },
      references: [
        'https://www.nhlbi.nih.gov/health/pneumonia',
        'https://www.nhlbi.nih.gov/health/pneumonia/diagnosis',
        'https://www.nhs.uk/symptoms/shortness-of-breath/',
      ],
    },
    {
      key: 'esophagus',
      identities: [
        [
          'FMA7131',
          'unpaired',
          'partof',
          ['FJ2563'],
          'thorax',
          ['thorax'],
          'organ',
        ],
      ],
      scope:
        'One source surface spans a passage, not independently segmented wall layers or a working lower oesophageal sphincter. The thorax browsing category does not limit its anatomical extent; no swallowing or reflux is simulated.',
      pathology: {
        body: 'Gastro-oesophageal reflux disease involves troublesome repeated reflux or complications from stomach contents entering the oesophagus. Possible complications include inflammation, narrowing and Barrett-related lining changes.',
        bullets: [
          'A stricture can interfere with swallowing. Barrett-related change is not inevitable and is not itself a diagnosis of cancer.',
          'Neither mucosal inflammation nor a change in cell type can be determined from this outer surface.',
        ],
      },
      clinical: {
        body: 'Distinguish difficulty swallowing from the return of swallowed material or heartburn. Swallowing difficulty, painful swallowing or unexplained weight loss require medical assessment rather than automatic attribution to simple reflux.',
        bullets: [
          'Chest discomfort may have non-oesophageal causes, including heart attack. In the UK, call 999 if a heart attack is suspected; do not use a reflux label to dismiss it.',
          'This lesson offers no endoscopic diagnosis, swallowing test or individual treatment recommendation.',
        ],
      },
      references: [
        'https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults/definition-facts',
        'https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults/symptoms-causes',
        'https://www.nhs.uk/conditions/heart-attack/',
      ],
    },
    {
      key: 'trachea',
      identities: [
        [
          'FMA7394',
          'unpaired',
          'partof',
          ['FJ2541'],
          'thorax',
          ['thorax'],
          'organ',
        ],
      ],
      scope:
        'A source-labelled tracheal surface, not a measured lumen, complete wall-layer model or validated device route. The cervical course is not excluded by its thorax browsing assignment.',
      pathology: {
        body: 'Tracheal stenosis narrows the central airway. It can follow intubation or tracheostomy; inflammatory disease, injury and other causes also require consideration.',
        bullets: [
          'Central-airway narrowing can produce noisy breathing, cough and breathlessness, sometimes resembling poorly responsive asthma.',
          'Moving, clipping or making this surface transparent does not reproduce a stenosis or establish airway patency.',
        ],
      },
      clinical: {
        body: 'Connect the symptoms and history to the level of the airway problem: a tracheal narrowing is not the same as disease of the larynx or small intrapulmonary airways. Clinical airway evaluation is needed to establish its location and severity.',
        bullets: [
          'In the UK, severe breathing difficulty or choking requires emergency help via 999.',
          'No intubation depth, stent size, tracheostomy site or procedural path can be planned from this mesh.',
        ],
      },
      references: [
        'https://www.pennmedicine.org/conditions/airway-stenosis',
        'https://www.nhs.uk/symptoms/shortness-of-breath/',
      ],
    },
    {
      key: 'thymus',
      identities: [
        [
          'FMA9607',
          'unpaired',
          'partof',
          ['FJ3150', 'FJ3151'],
          'thorax',
          ['thorax'],
          'organ',
        ],
      ],
      scope:
        "Two recovered source components form one selectable thymus. This fixed reference does not represent a patient's age-related involution, histology, immune activity or a mediastinal tumour.",
      pathology: {
        body: 'Thymoma and thymic carcinoma are distinct epithelial tumours of the thymus. Thymoma can be associated with autoimmune disease, particularly myasthenia gravis; the association does not make either diagnosis interchangeable.',
        bullets: [
          'A visible or large-looking thymus in this atlas is not evidence of a tumour.',
          'Normal developmental variation, a mass and its tissue diagnosis cannot be distinguished using this reference shape alone.',
        ],
      },
      clinical: {
        body: 'Consider a thymic lesion within the anterior mediastinal context and separate local effects from associated immune-mediated disease. Some tumours are discovered without symptoms; cough, breathlessness or chest discomfort are not specific to thymic disease.',
        bullets: [
          'Clinical assessment and appropriate imaging/tissue evaluation establish the nature and extent of a real lesion.',
          'The atlas cannot determine tumour type, stage, autoimmune status or whether an operation is appropriate.',
        ],
      },
      references: [
        'https://www.cancer.gov/types/thymus-cancer/thymoma-thymic-carcinoma',
      ],
    },
    {
      key: 'main-bronchi',
      identities: [
        [
          'FMA7395',
          'right',
          'partof',
          ['FJ2539'],
          'thorax',
          ['thorax'],
          'organ',
        ],
        ['FMA7396', 'left', 'isa', ['FJ2450'], 'thorax', ['thorax'], 'organ'],
      ],
      scope:
        'Two separately indexed proximal segments: the right uses PART-OF and the left ISA. Neither is a complete bronchial tree or a validated lumen. The paediatric clinical reference does not validate this adult reference model for children.',
      pathology: {
        body: 'An inhaled foreign body can obstruct a bronchus and lead to air trapping, collapse or subsequent infection. In children, persistent cough or a focal wheeze may follow an unwitnessed or earlier choking episode.',
        bullets: [
          'The effects depend on the site and degree of blockage, not simply whether the selected side is right or left.',
          'Anatomical orientation is not a rule that a foreign body must enter the right bronchus; no trajectory or lodged object is simulated.',
        ],
      },
      clinical: {
        body: 'In a child with possible foreign-body inhalation, a reassuring examination or normal chest radiograph does not exclude it. The history and persistent respiratory findings require clinical assessment; the atlas cannot clear an airway or rule out an obstruction.',
        bullets: [
          'In the UK, severe breathing difficulty or choking requires emergency help via 999.',
          'No retrieval manoeuvre, bronchoscopy technique, device route or procedural decision is provided.',
        ],
      },
      references: [
        'https://www.rch.org.au/clinicalguide/guideline_index/Foreign_bodies_inhaled/',
        'https://www.nhs.uk/symptoms/shortness-of-breath/',
      ],
    },
  ];
const byFma = new Map(
  thoracicOrganClinicalGroups.flatMap((group) =>
    group.identities.map(
      (identity) => [identity[0], { group, identity }] as const,
    ),
  ),
);
const same = (a: readonly string[], b: readonly string[]) =>
  a.length === b.length && a.every((v, i) => v === b[i]);

export function thoracicOrganClinicalLesson(
  s: BodyStructure,
  tab: ContentTab,
): ContentLesson | undefined {
  if ((tab !== 'pathology' && tab !== 'clinical') || s.system !== 'organs')
    return undefined;
  const match = byFma.get(s.fmaId);
  if (!match) return undefined;
  const [, side, tree, files, region, regions, category] = match.identity;
  if (
    s.category !== category ||
    s.laterality !== side ||
    s.sourceTree !== tree ||
    s.region !== region ||
    !same(s.regions, regions) ||
    !same(
      s.sources.map((p) => p.file),
      files,
    )
  )
    return undefined;
  const { group } = match,
    topic = group[tab];
  return {
    readiness: 'draft',
    title: `${s.name} · ${tab === 'pathology' ? 'Injury & disease' : 'Clinical context'} · draft`,
    body: topic.body,
    bullets: [...topic.bullets, group.scope],
    note: [
      'Draft teaching; independent anatomical and clinical review pending. Educational context, not a patient diagnosis or treatment plan.',
      s.coverageNote,
    ]
      .filter(Boolean)
      .join(' '),
    citations: [...group.references],
  };
}
