import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Intended use", description: "The intended-use boundary for Visible Medicine.", robots: { index: true, follow: true } };

const allowed = ["Radiological and pathological anatomy education", "Curated teaching cases and assessments", "Non-clinical research and educational evaluation", "Institution-delivered courses and learner progress records"];
const excluded = ["Diagnosis, differential diagnosis or clinical reporting", "Patient care, triage, treatment or clinical decisions", "Primary storage, retrieval or routing of clinical images", "Clinical credentialing, licensing or proof of diagnostic competence"];

export default function IntendedUsePage() {
  return <main className="inner-page intended-use-page"><section className="page-hero intended-use-hero"><p className="eyebrow"><span /> Product boundary</p><h1>Education and research only.</h1><p>Visible Medicine is a separate learning platform. It is not Didanix PACS and is not intended to support diagnosis, reporting or patient care.</p></section><section className="use-matrix"><div className="allowed"><span>Within intended use</span><h2>Teaching, learning and research</h2><ul>{allowed.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="excluded"><span>Outside intended use</span><h2>Clinical and diagnostic activity</h2><ul>{excluded.map((item) => <li key={item}>{item}</li>)}</ul></div></section><section className="boundary-enforcement"><div><p className="section-index">How the boundary is enforced</p><h2>Separated in language, identity, data and release.</h2></div><ol><li><b>Product language</b><span>Persistent intended-use notices and no diagnostic claims.</span></li><li><b>Identity</b><span>Education accounts and institution roles do not grant clinical access.</span></li><li><b>Data</b><span>Teaching media is quarantined, de-identified, rights checked and stored separately.</span></li><li><b>Release</b><span>Atlas and course publications require governed education review.</span></li></ol></section><section className="trust-actions"><Link className="primary-button" href="/trust">Open trust centre <span>→</span></Link><Link className="outline-button" href="/research">Research framework <span>→</span></Link></section></main>;
}
